=== WortTech/coreplus/docs/schemas/component.dtd
<!--
    PUBLIC ID: -//coreplus//vocabulary//EN
    SYSTEM ID: http://corepl.us/api/2_4/component.dtd

	Last revision date: 2013.12.03
-->

<!--
	An example how to use this DTD from your XML document:

	<?xml version="1.0"?>
	<!DOCTYPE component SYSTEM "http://corepl.us/api/2_4/component.dtd">

	<component>
	...
	</component>
-->

<!--
	Component is the main container for everything for a given... well, component.
	It's the root node, and each component can only contain one component.xml, which contains only one component directive.

	The component directive MUST have a name and version attribute.
	The name MUST match the component's directory, (capitalization is optional).
	The version SHOULD start with a number, and ideally have minor and point revisions, optionally with a third party flag at the end.
-->
<!ELEMENT component (licenses|authors|files|install|(otherfiles|requires|provides|hooks|smartyplugins|includes|pages|view|description|configs|users|userconfigs|assets|upgrades|forms|widgets|permissions)?)>
<!ATTLIST component
	execmode (web|cli|both) "web"
	name CDATA #REQUIRED
	version CDATA #REQUIRED
	xmlns:xsi CDATA #FIXED "http://www.w3.org/2001/XMLSchema-instance"
>

<!--
	Provides element is a list of provide statements indicating what this component has.
	A <provides> block MUST have one or more <provide> statement within.
-->
<!ELEMENT provides (provide|scriptlibrary)+>

<!ELEMENT provide EMPTY>
<!ATTLIST provide
version CDATA #REQUIRED
name CDATA #REQUIRED
type CDATA #IMPLIED
>
<!ELEMENT scriptlibrary EMPTY>
<!ATTLIST scriptlibrary
	name CDATA #REQUIRED
	call CDATA #IMPLIED
	>

<!ELEMENT forms (formelement)>
<!ELEMENT formelement EMPTY>
<!ATTLIST formelement name CDATA #REQUIRED class CDATA #REQUIRED>

<!ELEMENT requires (require)+>

<!ELEMENT require EMPTY>
<!ATTLIST require
	name CDATA #REQUIRED
	type CDATA #REQUIRED
	version CDATA #IMPLIED
	operation (lt|le|eq|ge|gt) "ge"
	>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT hooks (hookregister|hook)*>

<!ELEMENT hookregister EMPTY>
<!ATTLIST hookregister
	name CDATA #REQUIRED
	description CDATA #IMPLIED
	return (array|bool|string|void) "bool"
	>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT hook EMPTY>
<!ATTLIST hook
	name CDATA #REQUIRED
	call CDATA #REQUIRED
	>

<!--
	Smarty plugins root directive.
	Contains the directory functional plugins are located in and its children can be the individual calls.
-->
<!ELEMENT smartyplugins (smartyplugin)*>
<!ATTLIST smartyplugins
	directory CDATA #REQUIRED
	>

<!-- An individual smarty plugin registration.  Useful if you want to namespace your classes or organize them differently. -->
<!ELEMENT smartyplugin EMPTY>
<!ATTLIST
	name CDATA #REQUIRED
	call CDATA #REQUIRED
	>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT includes (include)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT include EMPTY>
<!ATTLIST include
	filename CDATA #REQUIRED
	>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT files (file)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT file (class|interface|widget|controller)*>
<!ATTLIST file
	md5 CDATA #IMPLIED
	filename CDATA #REQUIRED
	>

<!ELEMENT class EMPTY>
<!ATTLIST class
	name CDATA #REQUIRED
>

<!ELEMENT interface EMPTY>
<!ATTLIST interface
	name CDATA #REQUIRED
>

<!ELEMENT controller EMPTY>
<!ATTLIST controller
	name CDATA #REQUIRED
>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT pages (page)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT page EMPTY>
<!ATTLIST page
	baseurl CDATA #REQUIRED
	rewriteurl CDATA #IMPLIED
	title CDATA #REQUIRED
	access CDATA #IMPLIED
	admin (0|1) "0"
	group CDATA #IMPLIED
	selectable (0|1) "1"
>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT widgets (widget)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT widget EMPTY>
<!ATTLIST widget
	baseurl CDATA #REQUIRED
	title CDATA #IMPLIED
	installable CDATA #IMPLIED
>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT view (file)*>
<!ATTLIST view
	searchdir CDATA #IMPLIED
>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT install (dataset|phpfileinclude|php|sql)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT description (#PCDATA)>

<!--- Set of site configuration options -->
<!ELEMENT configs (config)*>

<!--- Each configuration option, editable from within system configuration -->
<!ELEMENT config EMPTY>
<!ATTLIST config
	key CDATA #REQUIRED
	type (string|int|boolean|enum|set) 'string'
	options CDATA #IMPLIED
	description CDATA #IMPLIED
	default CDATA #IMPLIED
	mapto CDATA #IMPLIED
>

<!-- 2.8.x User options, all contained within the <user/> key -->
<!ELEMENT users (userconfig|userauth)*>

<!--- pre-2.8.x User config options, since they're usually defined by the components. -->
<!ELEMENT userconfigs (userconfig)*>

<!--- The actual user configuration option, contained within uesrconfigs -->
<!ELEMENT userconfig EMPTY>
<!ATTLIST userconfig
	key CDATA #REQUIRED
	name CDATA #REQUIRED
	formtype CDATA #IMPLIED
	default CDATA #IMPLIED
	options CDATA #IMPLIED
	weight CDATA #IMPLIED
	onregistration (0|1) "1"
	onedit (0|1) "1"
	hidden (0|1) "0"
	searchable (0|1) "0"
	required (0|1) "0"
	validation CDATA #IMPLIED
>

<!ELEMENT userauth EMPTY>
<!ATTLIST userauth
	name CDATA #REQUIRED
	class CDATA #REQUIRED
>

<!--- Permissions contain all permissions used in this component -->
<!ELEMENT permissions (permission)*>

<!--
  - Each permission that is used throughout the component, useful for displaying the names in the group admin
  - Must have a "key" attribute that will be used to check for that permission throughout the site.
  - Should have a "description" attribute that will describe to the system admin what this permission does.
  - May have a "context" attribute that indicates to the system that it must be bound to a Model with the given basename.
  -->
<!ELEMENT permission EMPTY>
<!ATTLIST permission
	key CDATA #REQUIRED
	description CDATA #IMPLIED
	context CDATA #IMPLIED
>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT assets (file)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT upgrades (upgrade)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT upgrade (dataset|phpfileinclude|php|sql)*>
<!ATTLIST upgrade
	to CDATA #IMPLIED
	from CDATA #IMPLIED
>

<!-- Execute a SQL file, (after transposed through the dataset abstraction system) -->
<!ELEMENT sql EMPTY>
<!ATTLIST sql
	file CDATA #REQUIRED "The sql file to execute, relative to the component directory"
>

<!--
Execute a low-level dataset operation on the installation or upgrade.
-->
<!ELEMENT dataset (datasetset|datasetwhere|datasetrenamecolumn)*>
<!ATTLIST dataset
	action (update|insert|delete|alter) #REQUIRED
	table CDATA #REQUIRED
>

<!--
	The "SET" clause for datasets.  Useful for UPDATE and INSERT statements.
	The only attribute (which is required), is "key" and the nodeValue is the value that is set for that key.
-->
<!ELEMENT datasetset (#PCDATA)>
<!ATTLIST datasetset
	key CDATA #REQUIRED
>

<!--
	The "WHERE" clause for datasets.  Useful for all types of statements.
	The nodeValue here is the where statement, which is parsed via the dataset system.
-->
<!ELEMENT datasetwhere (#PCDATA)>

<!--
	The system cannot handle renames natively, as a renamed column in the schema is seen as a new column.
	This will allow you to rename a column in the schema during an upgrade.

	Please note, this is ONLY applicable with the "alter" action in the dataset.
-->
<!ELEMENT datasetrenamecolumn EMPTY>
<!ATTLIST datasetrenamecolumn
	oldname CDATA #REQUIRED
	newname CDATA #REQUIRED
>

<!-- The phpfileinclude allows upgrades and installs to call a custom php file to be executed automatically. -->
<!ELEMENT phpfileinclude (#PCDATA)>

<!-- The PHP element is a more short-hand version of phpfileinclude. -->
<!ELEMENT php EMPTY>
<!ATTLIST php
	file CDATA #REQUIRED "The filename, relative to the component directory"
>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT authors (author)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT author EMPTY>
<!ATTLIST author
	email CDATA #IMPLIED
	name CDATA #IMPLIED
>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT licenses (license)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT license (#PCDATA)>
<!ATTLIST license
	url CDATA #IMPLIED
>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT otherfiles (file)*>

=== WortTech/coreplus/src/components/gallery/component.xml
<?xml version="1.0"?>
<!DOCTYPE component PUBLIC "SYSTEM" "http://corepl.us/api/2_4/component.dtd">
<component xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.4.3" name="Gallery" execmode="web">
	<requires>
		<require name="core" type="component" version="2.5.6" operation="ge"/>
	</requires>
	<permissions>
		<permission key="gallery_manage" description="Manage Galleries"/>
	</permissions>
	<pages>
		<page baseurl="/gallery" admin="0" access="*" title="Gallery Listings"/>
		<page baseurl="/galleryadmin" admin="1" access="g:admin" title="Gallery Administration" group="Content"/>
	</pages>
	<description>
		Gallery browsing system for core+
	</description>
	<view searchdir="templates">
		<file filename="templates/pages/gallery/images_update.tpl" md5="b59d2b61005d91762fecae40ad768f46"/>
		<file filename="templates/pages/gallery/index.tpl" md5="27602f4c3d5cfda3605738666567dac9"/>
		<file filename="templates/pages/gallery/order.tpl" md5="fa1cd954ed88ab26a41857456ec6904a"/>
		<file filename="templates/pages/gallery/update.tpl" md5="5db5bf97680ec52e8ee5b5580af17daa"/>
		<file filename="templates/pages/gallery/updatelisting.tpl" md5="6795037bf2dc9bde8b4043b07839db46"/>
		<file filename="templates/pages/gallery/view-audio.tpl" md5="13cee03374835e963916b9e46ed450ac"/>
		<file filename="templates/pages/gallery/view-file.tpl" md5="3bee771a5c30d6b9d6d4727cc3f47cba"/>
		<file filename="templates/pages/gallery/view-image.tpl" md5="ffdf3d6faf3f0b639a3aa6cbbada585e"/>
		<file filename="templates/pages/gallery/view-video.tpl" md5="abe65b701c1834e7f4a8d270d8cf5915"/>
		<file filename="templates/pages/gallery/view.tpl" md5="51298cf90ff2f2f385409aaa4aa95284"/>
		<file filename="templates/pages/galleryadmin/images.tpl" md5="3eabcaf67ce559f286c8cb1c00340072"/>
		<file filename="templates/pages/galleryadmin/index.tpl" md5="65bb6129b2ee5b3fac36ee425d3a9141"/>
		<file filename="templates/pages/galleryadmin/widgets.tpl" md5="638e42be8f47518515b13955f0e8fc44"/>
		<file filename="templates/pages/galleryadmin/widgets_update.tpl" md5="6795037bf2dc9bde8b4043b07839db46"/>
		<file filename="templates/widgets/gallery/view.tpl" md5="1740eb2a852e7a72233cc0d89bb485d3"/>
	</view>
	<files>
		<file filename="CHANGELOG" md5="8081147de76df99a5d507ba943805412"/>
		<file filename="controllers/GalleryAdminController.php" md5="e7e9e24bac09986c379ccc1115a9db5b">
			<controller name="GalleryAdminController"/>
		</file>
		<file filename="controllers/GalleryController.php" md5="c6a2808a69951ac9bbbacc1232d0d887">
			<controller name="GalleryController"/>
		</file>
		<file filename="helpers/GalleryFormHandler.class.php" md5="6244b62dda32b5f6d3460d3e0b8393b7">
			<class name="GalleryFormHandler"/>
		</file>
		<file filename="models/GalleryAlbumModel.php" md5="f3cd17ade1ba1260d1f46dc2a42755a0">
			<class name="GalleryAlbumModel"/>
		</file>
		<file filename="models/GalleryImageModel.php" md5="eaeddd69dbfbfa24e946429e2daba11c">
			<class name="GalleryImageModel"/>
		</file>
		<file filename="upgrades/140_to_141_cachedtitles.php" md5="0e316e5f9a13a315331c93f1fc44b4dc"/>
		<file filename="widgets/GalleryWidget.php" md5="7daa22785667f4e5ec91e4991952114b">
			<class name="GalleryWidget"/>
		</file>
	</files>
	<assets>
		<file filename="assets/css/gallery.css" md5="e067bf7c123c06eda156cba4c5f1ea06"/>
		<file filename="assets/gallery-arrow.png" md5="16bc541d24d9c8d5a124369eb51a4f8e"/>
	</assets>
	<upgrades>
		<upgrade from="1.0.0" to="1.1.0"/>
		<upgrade from="1.1.0" to="1.1.1"/>
		<upgrade from="1.1.1" to="1.2.0"/>
		<upgrade from="1.2.0" to="1.3.0"/>
		<upgrade from="1.3.0" to="1.3.1"/>
		<upgrade from="1.3.1" to="1.3.2"/>
		<upgrade from="1.3.2" to="1.3.3"/>
		<upgrade from="1.3.3" to="1.4.0"/>
		<upgrade from="1.4.0" to="1.4.1">
			<phpfileinclude>
				components/gallery/upgrades/140_to_141_cachedtitles.php
			</phpfileinclude>
		</upgrade>
		<upgrade from="1.4.1" to="1.4.2"/>
		<upgrade from="1.4.2" to="1.4.3"/>
	</upgrades>
	<authors>
		<author name="Charlie Powell" email="charlie@eval.bz"/>
	</authors>
	<licenses>
		<license url="http://www.gnu.org/licenses/agpl-3.0.txt">
			GNU Affero General Public License v3
		</license>
	</licenses>
</component>

=== WortTech/coreplus/src/components/favicon/component.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component PUBLIC "SYSTEM" "http://corepl.us/api/2_4/component.dtd">
<component xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="Favicon" version="1.0.0">
	<description>
		A simple component to display a favicon for various browsers and mobile devices.
	</description>
	<configs>
		<config key="/favicon/image" type="string" description="Filename of the favicon"/>
	</configs>
	<pages>
		<page baseurl="/favicon/admin" title="Site Favicon" access="g:admin" admin="1" group="Configure"/>
	</pages>
	<hooks>
		<hook name="/core/page/rendering" call="FaviconController::PageHook"/>
	</hooks>
	<files>
		<file filename="CHANGELOG" md5="15007daa2cf64a2365cb8832b0cbc144"/>
		<file filename="README.md" md5="e758db0d8cb23bbfe0b3132575fed948"/>
		<file filename="controllers/FaviconController.php" md5="1abe734d489fd19057e1829fc167a178">
			<controller name="FaviconController"/>
		</file>
		<file filename="libs/favicon/ViewMeta_favicon.php" md5="9b0a11ca48105a938994268a24be92a2">
			<class name="ViewMeta_favicon"/>
		</file>
	</files>
	<view>
		<file filename="templates/pages/favicon/admin.tpl" md5="2556dd61a6b283b0fb6d614ae4d27831"/>
	</view>
	<requires>
		<require name="core" type="component" version="3.1.0" operation="ge"/>
	</requires>
	<authors>
		<author name="Charlie Powell" email="charlie@eval.bz"/>
	</authors>
	<licenses>
		<license url="http://www.gnu.org/licenses/agpl-3.0.txt">
			GNU Affero General Public License v3
		</license>
	</licenses>
</component>

=== WortTech/coreplus/src/components/markdown-browser/component.xml
<?xml version="1.0"?>
<!DOCTYPE component PUBLIC "SYSTEM" "http://corepl.us/api/2_4/component.dtd">
<component xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="2.0.0" name="Markdown Browser" execmode="web">
	<requires>
		<require name="core" type="component" version="4.9" operation="ge"/>
	</requires>
	<description>
		Provides an inline browser experience for raw markdown files on the server disk.
		This is expected to be used in conjunction with manually SFTP'ing files to the production server
		and having them automatically viewable on the live site as HTML pages.
		
		This DOES NOT provide functionality for editing those markdown files,
		as that is expected to be done via an external editor!
	</description>
	<configs>
		<config key="/markdownbrowser/basedir" type="string" default=""/>
		<config key="/markdownbrowser/source" type="boolean" default="1"/>
		<config key="/markdownbrowser/autoregister" type="boolean" default="0"/>
	</configs>
	<pages>
		<page baseurl="/markdownbrowser/admin" title="t:STRING_MARKDOWNBROWSER_ADMIN" admin="1" access="g:admin" group="Content"/>
	</pages>
	<hooks>
		<hook name="/cron/hourly" call="MarkdownBrowserController::_AutoRegisterFiles"/>
	</hooks>
	<files>
		<file filename="CHANGELOG" md5="8fb3b39e5768e85135eb3daa1582c5f3"/>
		<file filename="controllers/MarkdownBrowserController.php" md5="05815991b8837c0064065a7419f38f25">
			<controller name="MarkdownBrowserController"/>
			<class name="MarkdownBrowserUrlHelper"/>
		</file>
		<file filename="i18n/ar.ini" md5="ac804f50184b3da1cfa2a3e63e386ffd"/>
		<file filename="i18n/de.ini" md5="7ee24fe19d3916db8b649a176fba537b"/>
		<file filename="i18n/en.ini" md5="567a45f02dbef4435a852a8b4c58739a"/>
		<file filename="i18n/fr.ini" md5="a9a71c151f3671cb0a7299c68194eaa0"/>
	</files>
	<view searchdir="templates">
		<file filename="templates/pages/markdownbrowser/admin.tpl" md5="d13aab0a07c041db8dcec507e69990fa"/>
		<file filename="templates/pages/markdownbrowser/index.tpl" md5="2dfc8f64c4fe06140d998bc39464bbcf"/>
		<file filename="templates/pages/markdownbrowser/update.tpl" md5="6795037bf2dc9bde8b4043b07839db46"/>
		<file filename="templates/pages/markdownbrowser/view-file.tpl" md5="35d194b1b49f068ad8df448098ed7f7c"/>
	</view>
	<upgrades>
		<upgrade from="1.0.0" to="1.0.1"/>
		<upgrade from="1.0.1" to="1.0.2"/>
		<upgrade from="1.0.2" to="2.0.0"/>
	</upgrades>
	<users/>
	<widgets/>
	<authors>
		<author name="Charlie Powell" email="charlie@evalagency.com"/>
		<author name="Charlie Powell" email="charlie@eval.bz"/>
	</authors>
	<licenses>
		<license url="http://www.gnu.org/licenses/agpl-3.0.txt">
			GNU Affero General Public License v3
		</license>
	</licenses>
</component>

=== WortTech/coreplus/components/jquery-lightbox/component.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "http://corepl.us/api/2_1/component.dtd">
<component xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5~core1" name="JQuery-lightbox" execmode="web">
	<requires>
		<require name="core" type="component" version="2.1.0" operation="ge"/>
		<require name="jquery" type="library" version="1.4" operation="ge"/>
	</requires>
	<provides>
		<library name="JQuery.lightbox"/>
		<scriptlibrary name="jquery.lightbox" call="JQueryLightbox::Load"/>
	</provides>
	<assets>
		<file filename="assets/css/images/lightbox-blank.gif" md5="fc94fb0c3ed8a8f909dbc7630a0987ff"/>
		<file filename="assets/css/images/lightbox-btn-close.gif" md5="2c38ae5be85141bf8867c9523f4bc357"/>
		<file filename="assets/css/images/lightbox-btn-next.gif" md5="23414965ebe526012e473c1d4d65d4e7"/>
		<file filename="assets/css/images/lightbox-btn-prev.gif" md5="5a9118de4ef6226473190d6e82f6d80d"/>
		<file filename="assets/css/images/lightbox-ico-loading.gif" md5="b5fe8df97005341f898e2cf84e68de01"/>
		<file filename="assets/css/jquery.lightbox-0.5.css" md5="79ec543bbe42f8852aac14381b9ffff8"/>
		<file filename="assets/js/jquery.lightbox-0.5.js" md5="2f6bedebc6fde0a3f34626cc8815b344"/>
		<file filename="assets/js/jquery.lightbox-0.5.min.js" md5="21c9812998af15acf69da2f91bb02363"/>
	</assets>
	<files>
		<file filename="JQueryLightbox.lib.php" md5="f1602a583d6329c4120bf592148bab5e">
			<class name="JQueryLightbox"/>
		</file>
	</files>
	<description>
		Query lightBox plugin is simple, elegant, unobtrusive, no need extra markup and is used to overlay images on the current page through the power and flexibility of jQueryÂ´s selector.
		lightBox is a plugin for jQuery. It was inspired in Lightbox JS by Lokesh Dhakar.
		Visit http://leandrovieira.com/projects/jquery/lightbox/ for more informations about this jQuery plugin
	</description>
	<authors>
		<author name="Leandro Vieira Pinho"/>
	</authors>
	<licenses>
		<license url="http://creativecommons.org/licenses/by-sa/2.5/br/deed.en_US">
			CCAttribution-ShareAlike 2.5 Brazil
		</license>
	</licenses>
</component>

=== WortTech/coreplus/components/sitemap/component.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "http://corepl.us/api/2_1/component.dtd">
<component xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0.1" name="Sitemap" execmode="web">
	<requires>
		<require name="core" type="component" version="2.1.2"/>
	</requires>
	<files>
		<file filename="controllers/SitemapController.php" md5="ba28464ece7d3284aeaa81327e51599e">
			<controller name="SitemapController"/>
		</file>
	</files>
	<view>
		<file filename="templates/pages/sitemap/index.tpl" md5="ee04aea2710bd45bcd4a8d0e11bcb96f"/>
		<file filename="templates/pages/sitemap/index.xml.tpl" md5="eede649c57e8b937872919813f59b874"/>
	</view>
	<pages/>
	<assets/>
	<upgrades>
		<upgrade from="1.0.0" to="1.0.1"/>
	</upgrades>
	<authors>
		<author name="Charlie Powell" email="charlie@eval.bz"/>
	</authors>
	<licenses>
		<license url="http://www.gnu.org/licenses/agpl-3.0.txt">
			GNU Affero General Public License v3
		</license>
	</licenses>
</component>

=== WortTech/coreplus/components/security-suite/component.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "http://corepl.us/api/2_1/component.dtd">
<component xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0.0" name="Security-Suite" execmode="web">
	<requires>
		<require name="core" type="component" version="2.4.0"/>
	</requires>
	<configs></configs>
	<hooks>
		<hook name="/core/components/loaded" call="StopForumSpam::CheckIP"/>
		<hook name="/cron/daily" call="StopForumSpam::HookDaily"/>
	</hooks>
	<description>
		Collection of security suites for sites, including anti-spam.
	</description>
	<files>
		<file filename="classes/StopForumSpam.class.php" md5="f50aaa4e737571dac07780d301fc9328">
			<class name="StopForumSpam"/>
		</file>
		<file filename="listed_ip_1.zip" md5="9e6a0866ba2c7b797b0bbe39af7a6736"/>
		<file filename="models/SecurityLogModel.php" md5="e94c0c930142ba6df3ac961ead1643b9">
			<class name="SecurityLogModel"/>
		</file>
		<file filename="models/sfsBlacklistModel.php" md5="f23807f51bec4a8d271ad8735f8e237b">
			<class name="sfsBlacklistModel"/>
		</file>
	</files>
	<authors>
		<author name="Charlie Powell" email="charlie@eval.bz"/>
	</authors>
	<licenses>
		<license url="http://www.gnu.org/licenses/agpl-3.0.txt">
			GNU Affero General Public License v3
		</license>
	</licenses>
</component>

=== WortTech/coreplus/src/components/jquery-hoverintent/component.xml
<?xml version="1.0"?>
<!DOCTYPE component PUBLIC "SYSTEM" "http://corepl.us/api/2_4/component.dtd">
<component xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="r7~core2" name="JQuery-hoverIntent" execmode="web">
	<requires>
		<require name="core" type="component" version="2.1.0" operation="ge"/>
		<require name="jquery" type="library" version="1.7.2" operation="ge"/>
	</requires>
	<provides>
		<provide version="r7" name="JQuery.hoverIntent" type="library"/>
		<scriptlibrary name="jquery.hoverIntent" call="JQueryHoverIntent::Load"/>
	</provides>
	<assets>
		<file filename="assets/js/jquery.hoverIntent.min.js" md5="66de76b355f11c339085a2ac27621816"/>
	</assets>
	<upgrades>
		<upgrade from="r6~core1" to="r7~core1"/>
		<upgrade from="r7~core1" to="r7~core2"/>
	</upgrades>
	<files>
		<file filename="JQueryHoverIntent.lib.php" md5="aee32463fa0e30a75179e374e21ca641">
			<class name="JQueryHoverIntent"/>
		</file>
	</files>
	<description>
		hoverIntent is a plug-in that attempts to determine the user's intent...
		like a crystal ball, only with mouse movement! It works like (and was derived from)
		jQuery's built-in hover. However, instead of immediately calling the onMouseOver function,
		it waits until the user's mouse slows down enough before making the call.
	</description>
	<authors>
		<author name="Brian Cherne"/>
	</authors>
	<licenses>
		<license url="http://opensource.org/licenses/MIT">MIT and GPL licenses</license>
	</licenses>
</component>

=== WortTech/coreplus/components/user/component.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "http://corepl.us/api/2_1/component.dtd">
<component xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.9.1" name="user" execmode="web">
	<requires>
		<require name="core" type="component"/>
		<require name="Facebook" type="component"/>
	</requires>
	<smartyplugins directory="helpers/smarty-plugins/"/>
	<hooks>
		<hook name="/core/page/error-403" call="UserController::_HookHandler403"/>
	</hooks>
	<forms>
		<formelement name="access" class="FormAccessStringInput"/>
	</forms>
	<files>
		<file filename="CHANGELOG" md5="db582f5a38f5ebe7253037ee8181b59b"/>
		<file filename="Controllers/UserController.class.php" md5="fabc6777ac5a4e077f614497f5e41c2f">
			<controller name="UserController"/>
		</file>
		<file filename="Models/UserConfigModel.class.php" md5="3f9ec960d49d5a547038ddf3d91aeff2">
			<class name="UserConfigModel"/>
		</file>
		<file filename="Models/UserGroupModel.php" md5="4ad86ff7b1be60e1713195c4be07315d">
			<class name="UserGroupModel"/>
		</file>
		<file filename="Models/UserModel.class.php" md5="a99db3b236a330ddf9a1bb91d71e824d">
			<class name="UserModel"/>
		</file>
		<file filename="Models/UserUserConfigModel.class.php" md5="4bfc5564e1c98099374adf6de3bed563">
			<class name="UserUserConfigModel"/>
		</file>
		<file filename="User.class.php" md5="855a529712007bea2639958ee2b1d999">
			<class name="User"/>
			<class name="UserException"/>
		</file>
		<file filename="UserForm.class.php" md5="82dbfbb7871e415dfcc41fb7ff8bb1ad">
			<class name="FormAccessStringInput"/>
		</file>
		<file filename="User_Backend.interface.php" md5="699b8df9f6b8af73de189bdb0b0b1057">
			<interface name="User_Backend"/>
		</file>
		<file filename="Widgets/UserLoginWidget.class.php" md5="04d3602121f6cb231473284124dfa88f">
			<class name="UserLoginWidget"/>
		</file>
		<file filename="Widgets/UserWidget.class.php" md5="85affeee8ce7c56dad1e2ff6582bcb09">
			<class name="UserWidget"/>
		</file>
		<file filename="backends/User_datamodel.backend.php" md5="52e3a06ab605f547a984793281865793">
			<class name="User_datamodel_Backend"/>
		</file>
		<file filename="backends/User_facebook.backend.php" md5="9b56ef72aac8afdeaf37f303c26f1005">
			<class name="User_facebook_Backend"/>
		</file>
		<file filename="helpers/UserFunctions.php" md5="e1d98eef6534affb7bbaabbd682996cb"/>
		<file filename="helpers/smarty-plugins/block.permission.php" md5="d0bc40bbf5a9e48ee2331fcfb10bf408"/>
	</files>
	<view>
		<file filename="templates/widgets/userlogin.tpl" md5="8a8d32b7f36e7ee581ece66be94b4d2d"/>
		<file filename="templates/emails/user/forgotpassword.tpl" md5="3cceaf071bb8cd76a9f7c15fcc1da84e"/>
		<file filename="templates/emails/user/registration.tpl" md5="bc0af99c272dc0849608642ef56185f2"/>
		<file filename="templates/pages/user/register.tpl" md5="6795037bf2dc9bde8b4043b07839db46"/>
		<file filename="templates/pages/user/forgotpassword.tpl" md5="c2da0dced97b6b643b20c40a5046b5d1"/>
		<file filename="templates/pages/user/login.tpl" md5="b499441b575fa4bd2e7dd9ac2e49f52b"/>
		<file filename="templates/forms/elements/formaccessstringinput.tpl" md5="f230fcddefd98780d34bb7a9b3a38ac5"/>
		<file filename="templates/widgets/userlogin/execute.tpl" md5="8a8d32b7f36e7ee581ece66be94b4d2d"/>
		<file filename="templates/widgets/user/login.tpl" md5="74b44e98b27d05efd66ba03a377a8816"/>
		<file filename="templates/widgets/user/register.tpl" md5="6795037bf2dc9bde8b4043b07839db46"/>
		<file filename="templates/widgets/userlogin/execute.tpl" md5="8b33f6adb9fdadf3a6f4e10f6722de2e"/>
	</view>
	<pages>
		<page baseurl="/User/Login" admin="0" widget="0" access="!g:authenticated" title="Login"/>
		<page baseurl="/User/Register" admin="0" widget="0" access="!g:authenticated" title="Register"/>
		<page baseurl="/User/Logout" admin="0" widget="0" access="g:authenticated" title="Logout"/>
	</pages>
	<widgets>
		<widget baseurl="/UserWidget/Login"/>
		<widget baseurl="/UserWidget/Register"/>
	</widgets>
	<configs>
		<config key="/user/register/requirecaptcha" type="boolean" default="0" description=""/>
		<config key="/user/backends" type="set" default="datamodel" description="" options="datamodel| facebook| ldap"/>
		<config key="/user/password/minlength" type="int" default="8" description=""/>
		<config key="/user/password/requiresymbols" type="int" default="0" description=""/>
		<config key="/user/password/requirecapitals" type="int" default="0" description=""/>
		<config key="/user/displayname/displayoptions" type="set" options="username|firstname|emailbase|emailfull" default="username|firstname|emailbase" description=""/>
		<config key="/user/displayname/anonymous" type="string" default="Guest" description=""/>
		<config key="/user/displayname/authenticated" type="string" default="Member" description=""/>
		<config key="/user/register/allowpublic" type="boolean" default="true" description="Allow public registrations"/>
	</configs>
	<assets>
		<file filename="assets/js/user/login.js" md5="f48e188960e94f209e89f5168b101983"/>
		<file filename="assets/js/user/user.js" md5="b8793bfd7cd6ebeb3a9889905b300f7a"/>
	</assets>
	<description>
		The user component provides core user functionality, including registration, login, forgot password and access controls.
	</description>
	<otherfiles>
		<file filename="helpers/smarty-plugins/block.permission.php" md5="f909ae6c68833e4dc221594f3472d94d"/>
	</otherfiles>
	<upgrades>
		<upgrade from="0.0.1-dev1" to="0.0.2"/>
		<upgrade from="0.0.2" to="0.0.3"/>
		<upgrade from="0.0.3" to="1.9.0"/>
		<upgrade from="1.9.0" to="1.9.1">
			<dataset action="update" table="widget">
				<datasetset key="baseurl">/userwidget/login</datasetset>
				<datasetwhere>
					baseurl = /UserLoginWidget/execute
				</datasetwhere>
			</dataset>
		</upgrade>
	</upgrades>
	<authors>
		<author name="Charlie Powell" email="charlie@eval.bz"/>
	</authors>
	<licenses>
		<license url="http://www.gnu.org/licenses/agpl-3.0.txt">
			GNU Affero General Public License v3
		</license>
	</licenses>
</component>
