=== WortTech/coreplus/docs/schemas/component.dtd
<!--
    PUBLIC ID: -//coreplus//vocabulary//EN
    SYSTEM ID: http://corepl.us/api/2_4/component.dtd

	Last revision date: 2013.12.03
-->

<!--
	An example how to use this DTD from your XML document:

	<?xml version="1.0"?>
	<!DOCTYPE component SYSTEM "http://corepl.us/api/2_4/component.dtd">

	<component>
	...
	</component>
-->

<!--
	Component is the main container for everything for a given... well, component.
	It's the root node, and each component can only contain one component.xml, which contains only one component directive.

	The component directive MUST have a name and version attribute.
	The name MUST match the component's directory, (capitalization is optional).
	The version SHOULD start with a number, and ideally have minor and point revisions, optionally with a third party flag at the end.
-->
<!ELEMENT component (licenses|authors|files|install|(otherfiles|requires|provides|hooks|smartyplugins|includes|pages|view|description|configs|users|userconfigs|assets|upgrades|forms|widgets|permissions)?)>
<!ATTLIST component
	execmode (web|cli|both) "web"
	name CDATA #REQUIRED
	version CDATA #REQUIRED
	xmlns:xsi CDATA #FIXED "http://www.w3.org/2001/XMLSchema-instance"
>

<!--
	Provides element is a list of provide statements indicating what this component has.
	A <provides> block MUST have one or more <provide> statement within.
-->
<!ELEMENT provides (provide|scriptlibrary)+>

<!ELEMENT provide EMPTY>
<!ATTLIST provide
version CDATA #REQUIRED
name CDATA #REQUIRED
type CDATA #IMPLIED
>
<!ELEMENT scriptlibrary EMPTY>
<!ATTLIST scriptlibrary
	name CDATA #REQUIRED
	call CDATA #IMPLIED
	>

<!ELEMENT forms (formelement)>
<!ELEMENT formelement EMPTY>
<!ATTLIST formelement name CDATA #REQUIRED class CDATA #REQUIRED>

<!ELEMENT requires (require)+>

<!ELEMENT require EMPTY>
<!ATTLIST require
	name CDATA #REQUIRED
	type CDATA #REQUIRED
	version CDATA #IMPLIED
	operation (lt|le|eq|ge|gt) "ge"
	>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT hooks (hookregister|hook)*>

<!ELEMENT hookregister EMPTY>
<!ATTLIST hookregister
	name CDATA #REQUIRED
	description CDATA #IMPLIED
	return (array|bool|string|void) "bool"
	>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT hook EMPTY>
<!ATTLIST hook
	name CDATA #REQUIRED
	call CDATA #REQUIRED
	>

<!--
	Smarty plugins root directive.
	Contains the directory functional plugins are located in and its children can be the individual calls.
-->
<!ELEMENT smartyplugins (smartyplugin)*>
<!ATTLIST smartyplugins
	directory CDATA #REQUIRED
	>

<!-- An individual smarty plugin registration.  Useful if you want to namespace your classes or organize them differently. -->
<!ELEMENT smartyplugin EMPTY>
<!ATTLIST
	name CDATA #REQUIRED
	call CDATA #REQUIRED
	>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT includes (include)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT include EMPTY>
<!ATTLIST include
	filename CDATA #REQUIRED
	>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT files (file)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT file (class|interface|widget|controller)*>
<!ATTLIST file
	md5 CDATA #IMPLIED
	filename CDATA #REQUIRED
	>

<!ELEMENT class EMPTY>
<!ATTLIST class
	name CDATA #REQUIRED
>

<!ELEMENT interface EMPTY>
<!ATTLIST interface
	name CDATA #REQUIRED
>

<!ELEMENT controller EMPTY>
<!ATTLIST controller
	name CDATA #REQUIRED
>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT pages (page)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT page EMPTY>
<!ATTLIST page
	baseurl CDATA #REQUIRED
	rewriteurl CDATA #IMPLIED
	title CDATA #REQUIRED
	access CDATA #IMPLIED
	admin (0|1) "0"
	group CDATA #IMPLIED
	selectable (0|1) "1"
>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT widgets (widget)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT widget EMPTY>
<!ATTLIST widget
	baseurl CDATA #REQUIRED
	title CDATA #IMPLIED
	installable CDATA #IMPLIED
>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT view (file)*>
<!ATTLIST view
	searchdir CDATA #IMPLIED
>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT install (dataset|phpfileinclude|php|sql)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT description (#PCDATA)>

<!--- Set of site configuration options -->
<!ELEMENT configs (config)*>

<!--- Each configuration option, editable from within system configuration -->
<!ELEMENT config EMPTY>
<!ATTLIST config
	key CDATA #REQUIRED
	type (string|int|boolean|enum|set) 'string'
	options CDATA #IMPLIED
	description CDATA #IMPLIED
	default CDATA #IMPLIED
	mapto CDATA #IMPLIED
>

<!-- 2.8.x User options, all contained within the <user/> key -->
<!ELEMENT users (userconfig|userauth)*>

<!--- pre-2.8.x User config options, since they're usually defined by the components. -->
<!ELEMENT userconfigs (userconfig)*>

<!--- The actual user configuration option, contained within uesrconfigs -->
<!ELEMENT userconfig EMPTY>
<!ATTLIST userconfig
	key CDATA #REQUIRED
	name CDATA #REQUIRED
	formtype CDATA #IMPLIED
	default CDATA #IMPLIED
	options CDATA #IMPLIED
	weight CDATA #IMPLIED
	onregistration (0|1) "1"
	onedit (0|1) "1"
	hidden (0|1) "0"
	searchable (0|1) "0"
	required (0|1) "0"
	validation CDATA #IMPLIED
>

<!ELEMENT userauth EMPTY>
<!ATTLIST userauth
	name CDATA #REQUIRED
	class CDATA #REQUIRED
>

<!--- Permissions contain all permissions used in this component -->
<!ELEMENT permissions (permission)*>

<!--
  - Each permission that is used throughout the component, useful for displaying the names in the group admin
  - Must have a "key" attribute that will be used to check for that permission throughout the site.
  - Should have a "description" attribute that will describe to the system admin what this permission does.
  - May have a "context" attribute that indicates to the system that it must be bound to a Model with the given basename.
  -->
<!ELEMENT permission EMPTY>
<!ATTLIST permission
	key CDATA #REQUIRED
	description CDATA #IMPLIED
	context CDATA #IMPLIED
>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT assets (file)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT upgrades (upgrade)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT upgrade (dataset|phpfileinclude|php|sql)*>
<!ATTLIST upgrade
	to CDATA #IMPLIED
	from CDATA #IMPLIED
>

<!-- Execute a SQL file, (after transposed through the dataset abstraction system) -->
<!ELEMENT sql EMPTY>
<!ATTLIST sql
	file CDATA #REQUIRED "The sql file to execute, relative to the component directory"
>

<!--
Execute a low-level dataset operation on the installation or upgrade.
-->
<!ELEMENT dataset (datasetset|datasetwhere|datasetrenamecolumn)*>
<!ATTLIST dataset
	action (update|insert|delete|alter) #REQUIRED
	table CDATA #REQUIRED
>

<!--
	The "SET" clause for datasets.  Useful for UPDATE and INSERT statements.
	The only attribute (which is required), is "key" and the nodeValue is the value that is set for that key.
-->
<!ELEMENT datasetset (#PCDATA)>
<!ATTLIST datasetset
	key CDATA #REQUIRED
>

<!--
	The "WHERE" clause for datasets.  Useful for all types of statements.
	The nodeValue here is the where statement, which is parsed via the dataset system.
-->
<!ELEMENT datasetwhere (#PCDATA)>

<!--
	The system cannot handle renames natively, as a renamed column in the schema is seen as a new column.
	This will allow you to rename a column in the schema during an upgrade.

	Please note, this is ONLY applicable with the "alter" action in the dataset.
-->
<!ELEMENT datasetrenamecolumn EMPTY>
<!ATTLIST datasetrenamecolumn
	oldname CDATA #REQUIRED
	newname CDATA #REQUIRED
>

<!-- The phpfileinclude allows upgrades and installs to call a custom php file to be executed automatically. -->
<!ELEMENT phpfileinclude (#PCDATA)>

<!-- The PHP element is a more short-hand version of phpfileinclude. -->
<!ELEMENT php EMPTY>
<!ATTLIST php
	file CDATA #REQUIRED "The filename, relative to the component directory"
>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT authors (author)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT author EMPTY>
<!ATTLIST author
	email CDATA #IMPLIED
	name CDATA #IMPLIED
>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT licenses (license)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT license (#PCDATA)>
<!ATTLIST license
	url CDATA #IMPLIED
>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT otherfiles (file)*>

=== WortTech/coreplus/components/blog/component.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "http://corepl.us/api/2_1/component.dtd">
<component xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.1.0" name="Blog" execmode="web">
	<requires>
		<require name="core" type="component" version="2.1.2" operation="ge"/>
	</requires>
	<permissions>
		<permission key="blog_manage" description="Manage Blogs"/>
	</permissions>
	<files>
		<file filename="CHANGELOG" md5="2b3c0bd0a6cab2108c1706372541c070"/>
		<file filename="controllers/BlogController.php" md5="cd5091afcdac35f31d1f4afbe22f527c">
			<controller name="BlogController"/>
		</file>
		<file filename="helpers/BlogHelper.php" md5="283487940f0c2b3aeb1bf590752e997c">
			<class name="BlogHelper"/>
		</file>
		<file filename="models/BlogArticleModel.php" md5="ed1cb08d304428994a06ebecfd6a27f4">
			<class name="BlogArticleModel"/>
		</file>
		<file filename="models/BlogArticleTagModel.php" md5="19113d6a799ff3b6012c99e22558720c">
			<class name="BlogArticleTagModel"/>
		</file>
		<file filename="models/BlogModel.php" md5="ea5583b821de87b3bc16443d3c14c7be">
			<class name="BlogModel"/>
		</file>
	</files>
	<pages>
		<page baseurl="/blog/admin" admin="1" widget="0" access="p:blog_manage" title="Blog Administration"/>
	</pages>
	<description>Blog system.</description>
	<view searchdir="templates">
		<file filename="templates/pages/blog/admin.tpl" md5="207445c551f7c2169d951b0a7b501e7c"/>
		<file filename="templates/pages/blog/article_create.tpl" md5="a6195cc78d3992aed8c907894ef8d9f2"/>
		<file filename="templates/pages/blog/article_update.tpl" md5="7188695d360bad19187f63c7da3fc2f8"/>
		<file filename="templates/pages/blog/create.tpl" md5="6795037bf2dc9bde8b4043b07839db46"/>
		<file filename="templates/pages/blog/update.tpl" md5="6795037bf2dc9bde8b4043b07839db46"/>
		<file filename="templates/pages/blog/view-blog-article.tpl" md5="1dcf8e2e960ec6c63ed9580a338c3e37"/>
		<file filename="templates/pages/blog/view-blog.tpl" md5="070dedce576bd0d23afec2f705a440ac"/>
	</view>
	<upgrades>
		<upgrade from="1.0.0" to="1.1.0"/>
	</upgrades>
	<authors>
		<author name="Charlie Powell" email="charlie@eval.bz"/>
	</authors>
	<licenses>
		<license url="http://www.gnu.org/licenses/agpl-3.0.txt">
			GNU Affero General Public License v3
		</license>
	</licenses>
</component>

=== WortTech/coreplus/components/gallery/component.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "http://corepl.us/api/2_1/component.dtd">
<component xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0.0" name="gallery" execmode="web">
	<requires>
		<require name="core" type="component" version="2.1.1" operation="ge"/>
	</requires>
	<pages>
		<page baseurl="/gallery" admin="0" widget="0" access="*" title="Gallery Listings"/>
		<page baseurl="/galleryadmin" admin="1" widget="0" access="g:admin" title="Gallery Administration"/>
	</pages>
	<description>
		Gallery browsing system for core+
	</description>
	<view searchdir="templates">
		<file filename="templates/pages/gallery/view.tpl" md5="ef782e2a6b2ad43f7ae88ae39e68b97d"/>
		<file filename="templates/pages/galleryadmin/index.tpl" md5="d6c36a14a84aba6b7cdf798385a20d50"/>
		<file filename="templates/pages/galleryadmin/update.tpl" md5="6795037bf2dc9bde8b4043b07839db46"/>
		<file filename="templates/pages/galleryadmin/images.tpl" md5="84906ba21bf6a5c5d1f853ca3f20779e"/>
		<file filename="templates/pages/galleryadmin/index.tpl" md5="febf82fd34317bf6a39ebac551165dff"/>
		<file filename="templates/pages/galleryadmin/update.tpl" md5="5db5bf97680ec52e8ee5b5580af17daa"/>
		<file filename="templates/pages/gallery/images_update.tpl" md5="bba1532b36d2154dfb7f5f4065dad389"/>
		<file filename="templates/pages/gallery/index.tpl" md5="0a628017e0f6133d27f0c57ac2cf542f"/>
		<file filename="templates/pages/gallery/update.tpl" md5="5db5bf97680ec52e8ee5b5580af17daa"/>
		<file filename="templates/pages/gallery/view-image.tpl" md5="e80e955a167f0126d1793482f5d303e4"/>
		<file filename="templates/pages/gallery/view.tpl" md5="0abe5d4dc397e3991db5f93f61511103"/>
		<file filename="templates/pages/galleryadmin/images.tpl" md5="3eabcaf67ce559f286c8cb1c00340072"/>
		<file filename="templates/pages/galleryadmin/index.tpl" md5="93aca2ab7228f28683172bf10dd85bb2"/>
	</view>
	<files>
		<file filename="controllers/GalleryAdminController.php" md5="a361c67337926084d99da37710b8989b">
			<controller name="GalleryAdminController"/>
		</file>
		<file filename="controllers/GalleryController.php" md5="33c356f2d55659fc34bae0ad9a7b26e5">
			<controller name="GalleryController"/>
		</file>
		<file filename="models/GalleryAlbumModel.php" md5="74a3e201f63a7797e478271ff710e09e">
			<class name="GalleryAlbumModel"/>
		</file>
		<file filename="models/GalleryImageModel.php" md5="c0a6702a0111aaee5882557c11f9b413">
			<class name="GalleryImageModel"/>
		</file>
	</files>
	<authors>
		<author name="Charlie Powell" email="charlie@eval.bz"/>
	</authors>
	<licenses>
		<license url="http://www.gnu.org/licenses/agpl-3.0.txt">
			GNU Affero General Public License v3
		</license>
	</licenses>
	<assets>
		<file filename="assets/css/gallery.css" md5="6f0f8f0088c31e977bc722408027bad3"/>
	</assets>
</component>

=== WortTech/coreplus/src/components/jplayer/component.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "http://corepl.us/api/2_1/component.dtd">
<component xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="2.2.0~core1" name="jPlayer" execmode="web">
	<requires>
		<require name="core" type="component"/>
		<require name="JQuery" type="library" version="1.4" operation="ge"/>
	</requires>
	<provides>
		<scriptlibrary name="jplayer" call="jPlayer::IncludeJPlayer"/>
	</provides>
	<upgrades>
		<upgrade from="2.0.0" to="2.0.0~cae2"/>
		<upgrade from="2.0.0~cae2" to="2.0.0~cae3"/>
		<upgrade from="2.0.0~cae3" to="2.1.0~core1"/>
		<upgrade from="2.1.0~core1" to="2.2.0~core1"/>
	</upgrades>
	<files>
		<file filename="CHANGELOG" md5="4a80dadc8ec706b8544c2090f5625d83"/>
		<file filename="jPlayer.class.php" md5="69a6964e300f3f2ee1340a819d5bb725">
			<class name="jPlayer"/>
		</file>
		<file filename="source/Jplayer.as" md5="23d49380b77459bf3ac71dcb08c6bc68"/>
		<file filename="source/Jplayer.fla" md5="c6c6cda92c97d94640b62b75b5de3044"/>
		<file filename="source/add-on/jplayer.playlist.js" md5="db507525d94792ed399ce529b11f7475"/>
		<file filename="source/add-on/jquery.jplayer.inspector.js" md5="c009339d6136287c282eca94144f12c7"/>
		<file filename="source/happyworm/jPlayer/JplayerEvent.as" md5="469d26829c45403ac7317f3a9425b305"/>
		<file filename="source/happyworm/jPlayer/JplayerMp3.as" md5="c2f436e4a9ffde1f40022c3c1b49c36c"/>
		<file filename="source/happyworm/jPlayer/JplayerMp4.as" md5="870b1a69bee5fbca99e204d1c506df26"/>
		<file filename="source/happyworm/jPlayer/JplayerStatus.as" md5="9864cf02a6d737ce2e4bfdb3271f2309"/>
		<file filename="source/jquery.jplayer.js" md5="48350ca54c1c6dc29c1fc531826fab0b"/>
	</files>
	<assets>
		<file filename="assets/css/skin/jPlayer_blue.monday_extd.psd" md5="dfdf38678f1037f9dfee8539eda4bb4a"/>
		<file filename="assets/css/skin/jplayer.blue.monday.css" md5="f485a8bb1459850bbaf670b3bb39c0e3"/>
		<file filename="assets/css/skin/jplayer.blue.monday.jpg" md5="0e0fdecc749a3e48cba25ae991154029"/>
		<file filename="assets/css/skin/jplayer.blue.monday.seeking.gif" md5="6459e146ed61caa28e8ede05beb520b8"/>
		<file filename="assets/css/skin/jplayer.blue.monday.video.play.png" md5="d736613748cb6f59e1ce86db5e58bee0"/>
		<file filename="assets/css/skin/spirites_blue.monday_2011.psd" md5="0afab271084584b60d4f642bd9d60d4f"/>
		<file filename="assets/js/jplayer.playlist.min.js" md5="58f29924f2e0951ab6cbeb7e502d350e"/>
		<file filename="assets/js/jquery.jplayer.inspector.js" md5="efdcfd5a92b8aa45743788331113d7eb"/>
		<file filename="assets/js/jquery.jplayer.min.js" md5="0ab0a4d5b0b17a5697f08c78f7750f65"/>
		<file filename="assets/js/popcorn.jplayer.js" md5="af75a155444d1fe964eef1be9ba245e2"/>
		<file filename="assets/swf/Jplayer.swf" md5="f85e71a50abbaf2a1866ef16d392a420"/>
	</assets>
	<authors>
		<author name="Mark J Panaghiston"/>
	</authors>
</component>

=== WortTech/coreplus/src/components/facebook/component.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "http://corepl.us/api/2_4/component.dtd">
<component xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="3.2.3-7" name="Facebook" execmode="web">
	<hooks>
		<hook name="/core/page/rendering" call="FacebookHelper::HookRenderPage"/>
		<hook name="/core/controllinks/usermodel" call="FacebookController::GetUserControlLinks"/>
	</hooks>
	<provides>
		<provide type="library" name="facebook-sdk" version="3.2.0"/>
		<scriptlibrary name="facebook" call="FacebookHelper::Includejs"/>
	</provides>
	<requires>
		<require name="user" type="library" version="2.8.0"/>
		<require name="core" type="component" version="3.5.0" operation="ge"/>
	</requires>
	<configs>
		<config key="/facebook/appid" mapto="FACEBOOK_APP_ID" type="string" default="" description="If you want to enable facebook connectivity, you need to create an &quot;app&quot; and enter that app's appid here."/>
		<!--<config key="/facebook/secretid" mapto="FACEBOOK_SECRET_ID" type="string" default="" description="The Facebook app secret, also required for connectivity to facebook apps."/>
		-->
		<config key="/facebook/appsecret" mapto="FACEBOOK_APP_SECRET" type="string" default="" description="The Facebook app secret, also required for connectivity to facebook apps."/>
	</configs>
	<users>
		<userconfig key="facebook_id" name="Facebook ID" hidden="1"/>
		<userconfig key="facebook_link" name="Facebook Link" hidden="1"/>
		<userconfig key="gender" name="Gender" onregistration="0" onedit="0" formtype="select" options="|Male|Female|Other"/>
		<userconfig key="facebook_access_token" name="Facebook Access Token (set on login)" hidden="1"/>
		<userauth name="facebook" class="\Facebook\UserAuth"/>
	</users>
	<view searchdir="templates">
		<file filename="templates/emails/facebook/enable_confirmation.tpl" md5="bb92457d47699f47892941267c00f83b"/>
		<file filename="templates/includes/user/facebook_login.tpl" md5="7546e92c592e0d7f1910a447c83f9ef5"/>
		<file filename="templates/pages/facebook/enable.tpl" md5="ef5061ca42ad0ad233b0b1db5175d96b"/>
		<file filename="templates/pages/facebook/login.tpl" md5="3271d46acd1a48dd6aec8c71dcc07862"/>
		<file filename="templates/widgets/facebook/login.tpl" md5="d2c35fdad4e78240358e39c4c4ee3db1"/>
	</view>
	<files>
		<file filename="CHANGELOG" md5="68d5381e829793e4a43f1ad5d47666b9"/>
		<file filename="FacebookHelper.class.php" md5="d7ac2466285ce37c587f9bb91e079aa9">
			<class name="FacebookHelper"/>
		</file>
		<file filename="controllers/FacebookController.php" md5="017e2b9f4ea2e44b60580b80347425e2">
			<controller name="FacebookController"/>
		</file>
		<file filename="i18n/strings.yml" md5="87b83d0ec84e6d05e62a718dd2e035d2"/>
		<file filename="libs/facebook-php-sdk/changelog.md" md5="31fce8336dd5a3f061686f19e19bd56d"/>
		<file filename="libs/facebook-php-sdk/composer.json" md5="5d17b681de9984e9af98629c2404f0a4"/>
		<file filename="libs/facebook-php-sdk/examples/example.php" md5="21f296ecba4b310c889ad661de54328d"/>
		<file filename="libs/facebook-php-sdk/examples/with_js_sdk.php" md5="555e738cb8c6b42834a5c5a2083bd3e6"/>
		<file filename="libs/facebook-php-sdk/readme.md" md5="b732598f748027abede8be4ef245bdb4"/>
		<file filename="libs/facebook-php-sdk/src/base_facebook.php" md5="8a5ce0443a3e1fa3634565fbe31badf9">
			<class name="FacebookApiException"/>
			<class name="BaseFacebook"/>
		</file>
		<file filename="libs/facebook-php-sdk/src/facebook.php" md5="439079e5184c24758e08f08313b8b659">
			<class name="Facebook"/>
		</file>
		<file filename="libs/facebook-php-sdk/src/fb_ca_chain_bundle.crt" md5="c4290b9deb70d0bef2f88b67fc68c8ec"/>
		<file filename="libs/facebook-php-sdk/tests/bootstrap.php" md5="b8bd1937c8d639841949a24e2fcdf983"/>
		<file filename="libs/facebook-php-sdk/tests/tests.php" md5="7d445aa0f8b042c65ddd9e703fe081c3">
			<class name="PHPSDKTestCase"/>
			<class name="TransientFacebook"/>
			<class name="FBRecordURL"/>
			<class name="FBRecordMakeRequest"/>
			<class name="FBPublic"/>
			<class name="PersistentFBPublic"/>
			<class name="FBCode"/>
			<class name="FBAccessToken"/>
			<class name="FBGetCurrentURLFacebook"/>
			<class name="FBPublicCookie"/>
			<class name="FBRewrite"/>
			<class name="FBPublicGetAccessTokenFromCode"/>
			<class name="FBPublicState"/>
		</file>
		<file filename="libs/facebook/UserAuth.php" md5="e5194d9bf27d63f65a5ebcf37b3a1144">
			<class name="Facebook\UserAuth"/>
		</file>
		<file filename="widgets/FacebookWidget.php" md5="fdb60f6c5cfefd6d5d52db5182f51fbd">
			<class name="FacebookWidget"/>
		</file>
	</files>
	<upgrades>
		<upgrade from="3.0.1~Core1" to="3.2.0~core1"/>
		<upgrade from="3.2.0~core1" to="3.2.0~core2"/>
		<upgrade from="3.2.0~core2" to="3.2.0~core3"/>
		<upgrade from="3.2.0~core3" to="3.2.0~core4"/>
		<upgrade from="3.2.0~core4" to="3.2.0~core5"/>
		<upgrade from="3.2.0~core5" to="3.2.0~core6"/>
		<upgrade from="3.2.0~core6" to="3.2.0~core7"/>
		<upgrade from="3.2.0~core7" to="3.2.0~core8"/>
		<upgrade from="3.2.0~core8" to="3.2.3~core1"/>
		<upgrade from="3.2.3~core1" to="3.2.3~core2"/>
		<upgrade from="3.2.3~core2" to="3.2.3~core3"/>
		<upgrade from="3.2.3~core3" to="3.2.3~core4"/>
		<upgrade from="3.2.3~core4" to="3.2.3~core5"/>
		<upgrade from="3.2.3~core5" to="3.2.3-6"/>
		<upgrade from="3.2.3-6" to="3.2.3-7"/>
	</upgrades>
	<assets>
		<file filename="assets/css/facebook.css" md5="705ee2ca2a443c5ff690c277ef26a2fe"/>
		<file filename="assets/js/facebook/login.js" md5="17a212d8244b41d712db7dbb480da122"/>
		<file filename="assets/js/facebook/login.min.js" md5="47160cc5f84a321aba41e44d4e786d22"/>
	</assets>
	<authors>
		<author name="Naitik Shah" email="naitik@facebook.com"/>
		<author name="Charlie Powell" email="charlie@evalagency.com"/>
	</authors>
	<licenses>
		<license url="http://www.gnu.org/licenses/agpl-3.0.txt">
			GNU Affero General Public License v3
		</license>
	</licenses>
</component>

=== WortTech/coreplus/src/components/blog/component.xml
<?xml version="1.0"?>
<!DOCTYPE component PUBLIC "SYSTEM" "http://corepl.us/api/2_4/component.dtd">
<component xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.5.1" name="Blog" execmode="web">
	<requires>
		<require name="core" type="component" version="2.6.0" operation="ge"/>
		<require name="user" type="component" version="2.5.4"/>
		<require name="tags" type="component"/>
		<require name="JQuery-Full" type="component" version="1.9"/>
	</requires>
	<permissions>
		<permission key="blog_manage" description="Manage Blogs"/>
	</permissions>
	<hooks>
		<hook name="/cron/daily" call="BlogHelper::CronRetrieveRemoteFeeds"/>
	</hooks>
	<files>
		<file filename="CHANGELOG" md5="76e20b7c3ec3f1a33b48827500dc753d"/>
		<file filename="controllers/BlogController.php" md5="a543e226d15503c04193fb914ba783bc">
			<controller name="BlogController"/>
		</file>
		<file filename="helpers/BlogHelper.php" md5="61accf39c5879f6f906892195e38c8d3">
			<class name="BlogHelper"/>
		</file>
		<file filename="models/BlogArticleModel.php" md5="1bf56c3b92dbe784f78ea05e41ea480a">
			<class name="BlogArticleModel"/>
		</file>
		<file filename="models/BlogModel.php" md5="37bc0cf4adbacd59cd96fcb68f39a080">
			<class name="BlogModel"/>
		</file>
		<file filename="upgrades/121_to_130.php" md5="4f71587ed4a65da58490523dd9581684"/>
		<file filename="upgrades/130_to_140_published.php" md5="4ab899aa7768154bde4f5197a7cfbf2b"/>
		<file filename="upgrades/130_to_140_selectable.php" md5="33c3b2e0c9456a6a900d7340f1c65c5b"/>
		<file filename="upgrades/150_to_151_filepathchange.php" md5="d37162704ef850a8954bf11dcc66dc43"/>
	</files>
	<pages>
		<page baseurl="/blog/admin" admin="1" access="p:blog_manage" title="Blog Administration" group="Content"/>
		<page baseurl="/blog" title="Blogs"/>
	</pages>
	<description>Blog system.</description>
	<view searchdir="templates">
		<file filename="templates/pages/blog/admin.tpl" md5="44274363e8c7fea512396a63293c63fd"/>
		<file filename="templates/pages/blog/admin_view.tpl" md5="e1ca90792ff8835bee5ef1d03c54a851"/>
		<file filename="templates/pages/blog/article_create_update.tpl" md5="843616082c6990b3d75dded8e08d9025"/>
		<file filename="templates/pages/blog/article_view.tpl" md5="ec825042c51643a9955fdcf9184e86fb"/>
		<file filename="templates/pages/blog/article_view/review-post.tpl" md5="f645ccbfa064359ed5962077ad666ddd"/>
		<file filename="templates/pages/blog/create.tpl" md5="88a92a02a91699df3f24063112502867"/>
		<file filename="templates/pages/blog/editindex.tpl" md5="6795037bf2dc9bde8b4043b07839db46"/>
		<file filename="templates/pages/blog/import.tpl" md5="7e3f8c90db26ba500fa9e3ee439d2655"/>
		<file filename="templates/pages/blog/index.tpl" md5="9a74ac7f89123b40f8421b02ec9a3887"/>
		<file filename="templates/pages/blog/update.tpl" md5="e2df73ed8b507c4318fa29588015a80f"/>
		<file filename="templates/pages/blog/view-blog.atom.tpl" md5="5e7fe2a6a81b5c70b69094dce22ee078"/>
		<file filename="templates/pages/blog/view-blog.rss.tpl" md5="dc2fd8c75e28eb869d068c1919654c96"/>
		<file filename="templates/pages/blog/view-blog.tpl" md5="86fcd7022a353f51f73a101985ab6823"/>
	</view>
	<upgrades>
		<upgrade from="1.0.0" to="1.1.0"/>
		<upgrade from="1.1.0" to="1.2.0"/>
		<upgrade from="1.2.0" to="1.2.1"/>
		<upgrade from="1.2.1" to="1.3.0">
			<phpfileinclude>
				components/blog/upgrades/121_to_130.php
			</phpfileinclude>
		</upgrade>
		<upgrade from="1.2.9a" to="1.3.0"/>
		<upgrade from="1.3.0" to="1.4.0">
			<phpfileinclude>
				components/blog/upgrades/130_to_140_published.php
			</phpfileinclude>
			<phpfileinclude>
				components/blog/upgrades/130_to_140_selectable.php
			</phpfileinclude>
		</upgrade>
		<upgrade from="1.4.0" to="1.4.1"/>
		<upgrade from="1.4.1" to="1.4.2">
			<!-- This will retro-actively fix bug #321. -->
			<dataset action="update" table="page">
				<datasetset key="selectable">0</datasetset>
				<datasetwhere>
					baseurl LIKE /blog/article/view%
				</datasetwhere>
			</dataset>
		</upgrade>
		<upgrade from="1.4.2" to="1.4.3"/>
		<upgrade from="1.4.3" to="1.4.4"/>
		<upgrade from="1.4.4" to="1.4.5"/>
		<upgrade from="1.4.5" to="1.5.0"/>
		<upgrade from="1.5.0" to="1.5.1">
			<phpfileinclude>
				components/blog/upgrades/150_to_151_filepathchange.php
			</phpfileinclude>
		</upgrade>
	</upgrades>
	<assets>
		<file filename="assets/css/blog.css" md5="525a38d44528503b891cc5b7a094b98e"/>
		<file filename="assets/images/valid-atom.png" md5="e343955a970cb2f7834fdb550f600ab2"/>
		<file filename="assets/images/valid-rss.png" md5="7dac8fdd319e86cf82fa27bc7e2d416f"/>
		<file filename="assets/js/blog-waypoint-scroll.js" md5="785bccef5ce4f802b581d91d26fff6c7"/>
	</assets>
	<authors>
		<author name="Charlie Powell" email="charlie@eval.bz"/>
	</authors>
	<licenses>
		<license url="http://www.gnu.org/licenses/agpl-3.0.txt">
			GNU Affero General Public License v3
		</license>
	</licenses>
</component>

=== WortTech/coreplus/src/components/php-markdown-lib/component.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component PUBLIC "SYSTEM" "http://corepl.us/api/2_4/component.dtd">
<component xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="PHP Markdown Lib" version="1.7.0" logo="assets/images/php-markdown-lib.png">
	<requires>
		<require name="core" type="component" version="6.2.0" operation="ge"/>
	</requires>
	<files>
		<file filename="CHANGELOG" md5="4af8ceff05dcc648c21dffa2eba6cb6a"/>
		<file filename="License.md" md5="1dbbf231d98ac9c5012342c2cf622f82"/>
		<file filename="Readme.md" md5="56053198424aae8f0661ca0e7d1d9f58"/>
		<file filename="Readme.php" md5="06c70305f1837db551b08b5e5729c55b"/>
		<file filename="composer.json" md5="f3c5c68eb29718d028ec13b97362485d"/>
		<file filename="libs/Core/Forms/MarkdownInput.php" md5="19d870fa6d46bdd9c0c92897209f0846">
			<class name="Core\Forms\MarkdownInput"/>
		</file>
		<file filename="libs/Core/MarkdownProcessor.php" md5="1e4d950a6898220a76287e60ecd6ea79">
			<class name="Core\MarkdownProcessor"/>
		</file>
		<file filename="libs/Michelf/Markdown.inc.php" md5="f998ac3927b4c09a63be0e8057ed1838"/>
		<file filename="libs/Michelf/Markdown.php" md5="6a7dfed22a693ce9d80a395fcdaa6a8e">
			<class name="Michelf\Markdown"/>
		</file>
		<file filename="libs/Michelf/MarkdownExtra.inc.php" md5="ae7333ba45bc314bc27390dc3224fb93"/>
		<file filename="libs/Michelf/MarkdownExtra.php" md5="5bc40b4ec8d2fafa4c7e78dea5ebcade">
			<class name="Michelf\MarkdownExtra"/>
		</file>
		<file filename="libs/Michelf/MarkdownInterface.inc.php" md5="98322ed9b914f9343a0ccafe2548b4cb"/>
		<file filename="libs/Michelf/MarkdownInterface.php" md5="7003f97abae9f65e16bfa161bd40daf1">
			<interface name="Michelf\MarkdownInterface"/>
		</file>
		<file filename="markdown.md" md5="462ca5b5d94ee7113eb0cab761cadf30"/>
	</files>
	<view>
		<file filename="templates/includes/forms/markdowninput.tpl" md5="39d600c155d7dc6f6e28a8d6e1661747"/>
	</view>
	<authors>
		<author name="Michel Fortin" email="michel.fortin@michelf.com"/>
		<author name="Charlie Powell" email="charlie@evalagency.com"/>
	</authors>
	<licenses>
		<license url="http://www.gnu.org/licenses/agpl-3.0.html">
			GNU Affero General Public License
		</license>
		<license url="https://opensource.org/licenses/BSD-3-Clause">3-Clause BSD License</license>
	</licenses>
	<assets>
		<file filename="assets/images/php-markdown-lib.png" md5="d190443d677bd4999176ce5bb8bb874f"/>
	</assets>
</component>
