=== WortTech/coreplus/docs/schemas/component.dtd
<!--
    PUBLIC ID: -//coreplus//vocabulary//EN
    SYSTEM ID: http://corepl.us/api/2_4/component.dtd

	Last revision date: 2013.12.03
-->

<!--
	An example how to use this DTD from your XML document:

	<?xml version="1.0"?>
	<!DOCTYPE component SYSTEM "http://corepl.us/api/2_4/component.dtd">

	<component>
	...
	</component>
-->

<!--
	Component is the main container for everything for a given... well, component.
	It's the root node, and each component can only contain one component.xml, which contains only one component directive.

	The component directive MUST have a name and version attribute.
	The name MUST match the component's directory, (capitalization is optional).
	The version SHOULD start with a number, and ideally have minor and point revisions, optionally with a third party flag at the end.
-->
<!ELEMENT component (licenses|authors|files|install|(otherfiles|requires|provides|hooks|smartyplugins|includes|pages|view|description|configs|users|userconfigs|assets|upgrades|forms|widgets|permissions)?)>
<!ATTLIST component
	execmode (web|cli|both) "web"
	name CDATA #REQUIRED
	version CDATA #REQUIRED
	xmlns:xsi CDATA #FIXED "http://www.w3.org/2001/XMLSchema-instance"
>

<!--
	Provides element is a list of provide statements indicating what this component has.
	A <provides> block MUST have one or more <provide> statement within.
-->
<!ELEMENT provides (provide|scriptlibrary)+>

<!ELEMENT provide EMPTY>
<!ATTLIST provide
version CDATA #REQUIRED
name CDATA #REQUIRED
type CDATA #IMPLIED
>
<!ELEMENT scriptlibrary EMPTY>
<!ATTLIST scriptlibrary
	name CDATA #REQUIRED
	call CDATA #IMPLIED
	>

<!ELEMENT forms (formelement)>
<!ELEMENT formelement EMPTY>
<!ATTLIST formelement name CDATA #REQUIRED class CDATA #REQUIRED>

<!ELEMENT requires (require)+>

<!ELEMENT require EMPTY>
<!ATTLIST require
	name CDATA #REQUIRED
	type CDATA #REQUIRED
	version CDATA #IMPLIED
	operation (lt|le|eq|ge|gt) "ge"
	>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT hooks (hookregister|hook)*>

<!ELEMENT hookregister EMPTY>
<!ATTLIST hookregister
	name CDATA #REQUIRED
	description CDATA #IMPLIED
	return (array|bool|string|void) "bool"
	>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT hook EMPTY>
<!ATTLIST hook
	name CDATA #REQUIRED
	call CDATA #REQUIRED
	>

<!--
	Smarty plugins root directive.
	Contains the directory functional plugins are located in and its children can be the individual calls.
-->
<!ELEMENT smartyplugins (smartyplugin)*>
<!ATTLIST smartyplugins
	directory CDATA #REQUIRED
	>

<!-- An individual smarty plugin registration.  Useful if you want to namespace your classes or organize them differently. -->
<!ELEMENT smartyplugin EMPTY>
<!ATTLIST
	name CDATA #REQUIRED
	call CDATA #REQUIRED
	>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT includes (include)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT include EMPTY>
<!ATTLIST include
	filename CDATA #REQUIRED
	>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT files (file)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT file (class|interface|widget|controller)*>
<!ATTLIST file
	md5 CDATA #IMPLIED
	filename CDATA #REQUIRED
	>

<!ELEMENT class EMPTY>
<!ATTLIST class
	name CDATA #REQUIRED
>

<!ELEMENT interface EMPTY>
<!ATTLIST interface
	name CDATA #REQUIRED
>

<!ELEMENT controller EMPTY>
<!ATTLIST controller
	name CDATA #REQUIRED
>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT pages (page)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT page EMPTY>
<!ATTLIST page
	baseurl CDATA #REQUIRED
	rewriteurl CDATA #IMPLIED
	title CDATA #REQUIRED
	access CDATA #IMPLIED
	admin (0|1) "0"
	group CDATA #IMPLIED
	selectable (0|1) "1"
>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT widgets (widget)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT widget EMPTY>
<!ATTLIST widget
	baseurl CDATA #REQUIRED
	title CDATA #IMPLIED
	installable CDATA #IMPLIED
>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT view (file)*>
<!ATTLIST view
	searchdir CDATA #IMPLIED
>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT install (dataset|phpfileinclude|php|sql)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT description (#PCDATA)>

<!--- Set of site configuration options -->
<!ELEMENT configs (config)*>

<!--- Each configuration option, editable from within system configuration -->
<!ELEMENT config EMPTY>
<!ATTLIST config
	key CDATA #REQUIRED
	type (string|int|boolean|enum|set) 'string'
	options CDATA #IMPLIED
	description CDATA #IMPLIED
	default CDATA #IMPLIED
	mapto CDATA #IMPLIED
>

<!-- 2.8.x User options, all contained within the <user/> key -->
<!ELEMENT users (userconfig|userauth)*>

<!--- pre-2.8.x User config options, since they're usually defined by the components. -->
<!ELEMENT userconfigs (userconfig)*>

<!--- The actual user configuration option, contained within uesrconfigs -->
<!ELEMENT userconfig EMPTY>
<!ATTLIST userconfig
	key CDATA #REQUIRED
	name CDATA #REQUIRED
	formtype CDATA #IMPLIED
	default CDATA #IMPLIED
	options CDATA #IMPLIED
	weight CDATA #IMPLIED
	onregistration (0|1) "1"
	onedit (0|1) "1"
	hidden (0|1) "0"
	searchable (0|1) "0"
	required (0|1) "0"
	validation CDATA #IMPLIED
>

<!ELEMENT userauth EMPTY>
<!ATTLIST userauth
	name CDATA #REQUIRED
	class CDATA #REQUIRED
>

<!--- Permissions contain all permissions used in this component -->
<!ELEMENT permissions (permission)*>

<!--
  - Each permission that is used throughout the component, useful for displaying the names in the group admin
  - Must have a "key" attribute that will be used to check for that permission throughout the site.
  - Should have a "description" attribute that will describe to the system admin what this permission does.
  - May have a "context" attribute that indicates to the system that it must be bound to a Model with the given basename.
  -->
<!ELEMENT permission EMPTY>
<!ATTLIST permission
	key CDATA #REQUIRED
	description CDATA #IMPLIED
	context CDATA #IMPLIED
>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT assets (file)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT upgrades (upgrade)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT upgrade (dataset|phpfileinclude|php|sql)*>
<!ATTLIST upgrade
	to CDATA #IMPLIED
	from CDATA #IMPLIED
>

<!-- Execute a SQL file, (after transposed through the dataset abstraction system) -->
<!ELEMENT sql EMPTY>
<!ATTLIST sql
	file CDATA #REQUIRED "The sql file to execute, relative to the component directory"
>

<!--
Execute a low-level dataset operation on the installation or upgrade.
-->
<!ELEMENT dataset (datasetset|datasetwhere|datasetrenamecolumn)*>
<!ATTLIST dataset
	action (update|insert|delete|alter) #REQUIRED
	table CDATA #REQUIRED
>

<!--
	The "SET" clause for datasets.  Useful for UPDATE and INSERT statements.
	The only attribute (which is required), is "key" and the nodeValue is the value that is set for that key.
-->
<!ELEMENT datasetset (#PCDATA)>
<!ATTLIST datasetset
	key CDATA #REQUIRED
>

<!--
	The "WHERE" clause for datasets.  Useful for all types of statements.
	The nodeValue here is the where statement, which is parsed via the dataset system.
-->
<!ELEMENT datasetwhere (#PCDATA)>

<!--
	The system cannot handle renames natively, as a renamed column in the schema is seen as a new column.
	This will allow you to rename a column in the schema during an upgrade.

	Please note, this is ONLY applicable with the "alter" action in the dataset.
-->
<!ELEMENT datasetrenamecolumn EMPTY>
<!ATTLIST datasetrenamecolumn
	oldname CDATA #REQUIRED
	newname CDATA #REQUIRED
>

<!-- The phpfileinclude allows upgrades and installs to call a custom php file to be executed automatically. -->
<!ELEMENT phpfileinclude (#PCDATA)>

<!-- The PHP element is a more short-hand version of phpfileinclude. -->
<!ELEMENT php EMPTY>
<!ATTLIST php
	file CDATA #REQUIRED "The filename, relative to the component directory"
>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT authors (author)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT author EMPTY>
<!ATTLIST author
	email CDATA #IMPLIED
	name CDATA #IMPLIED
>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT licenses (license)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT license (#PCDATA)>
<!ATTLIST license
	url CDATA #IMPLIED
>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT otherfiles (file)*>

=== WortTech/coreplus/components/fontawesome/component.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "http://corepl.us/api/2_1/component.dtd">
<component xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="2.0~core2" name="FontAwesome" execmode="web">
	<requires>
		<require name="core" type="component" version="2.1.0" operation="ge"/>
	</requires>
	<provides>
		<scriptlibrary name="fontawesome" call="FontAwesome::Load"/>
	</provides>
	<description>
		The iconic font designed for use with Twitter Bootstrap
	</description>
	<files>
		<file filename="FontAwesome-Vectors.pdf" md5="4bdcf9dc73a13c8f1c3bd6be6fd2de49"/>
		<file filename="FontAwesome.lib.php" md5="f390e22f306175178982dc0f275689b4">
			<class name="FontAwesome"/>
		</file>
		<file filename="README.md" md5="bcb91e0d16d1f010effa565d0c7980d2"/>
	</files>
	<assets>
		<file filename="assets/css/font-awesome-ie7.css" md5="461c93f69710a40e0bc6851a84ed76c9"/>
		<file filename="assets/css/font-awesome-tweaks.css" md5="ffa4ef1c9f29652091f87bdc56faafd0"/>
		<file filename="assets/css/font-awesome.css" md5="764eba9c7d44a3c91244ecee8736feac"/>
		<file filename="assets/font/fontawesome-webfont.eot" md5="5f4a40c122903174c4227e6871b88cff"/>
		<file filename="assets/font/fontawesome-webfont.svg" md5="13420cbc7af6227733d1a12e5df28fe9"/>
		<file filename="assets/font/fontawesome-webfont.ttf" md5="6ea09593203493bfd053a1e838c62404"/>
		<file filename="assets/font/fontawesome-webfont.woff" md5="04b9bfc362dcb9bc999c7d1bcb44a942"/>
	</assets>
	<upgrades>
		<upgrade from="2.0" to="2.0~core2"/>
	</upgrades>
	<authors>
		<author name="Dave Gandy" email="dave@davegandy.com"/>
	</authors>
	<licenses>
		<license url="http://creativecommons.org/licenses/by/3.0/">CC BY 3.0</license>
	</licenses>
</component>

=== WortTech/coreplus/src/components/navigation/component.xml
<?xml version="1.0"?>
<!DOCTYPE component PUBLIC "SYSTEM" "http://corepl.us/api/2_4/component.dtd">
<component xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="2.1.9" name="Navigation" execmode="web">
	<requires>
		<require name="core" type="component" operation="ge" version="2.5.6"/>
	</requires>
	<files>
		<file filename="CHANGELOG" md5="e6389cccc1b959677ca2058268b310e8"/>
		<file filename="controllers/NavigationController.php" md5="e1f41f41e41aff37a4098c14198f2327">
			<controller name="NavigationController"/>
		</file>
		<file filename="models/Navigation.model.php" md5="556a19051c430a73a838bcf5e44d09e7">
			<class name="NavigationModel"/>
		</file>
		<file filename="models/NavigationEntry.model.php" md5="86d030909068fa026a1e8d4ba1836dde">
			<class name="NavigationEntryModel"/>
		</file>
		<file filename="widgets/NavigationWidget.php" md5="8321c54fcb1743d2fbb80ad556ec7530">
			<class name="NavigationWidget"/>
		</file>
	</files>
	<view>
		<file filename="templates/pages/navigation/create.tpl" md5="75c1c4157d0b64b0f5e05fa3a0ee9846"/>
		<file filename="templates/pages/navigation/create_edit.inc.tpl" md5="4031fb3dc83afb83f716a6150a479a55"/>
		<file filename="templates/pages/navigation/delete.tpl" md5="76e1949488cb9acaaf83eb1a95c9abd5"/>
		<file filename="templates/pages/navigation/edit.tpl" md5="a6eda39bbc1a33dac2888ffe43ab7868"/>
		<file filename="templates/pages/navigation/index.tpl" md5="8fbbccd35a3cbc609cc8845b6a3a45ee"/>
		<file filename="templates/pages/navigation/view.tpl" md5="44b506f0e3ca0a1bfef9d5f4b992a8c0"/>
		<file filename="templates/widgets/navigation/_menu.inc.tpl" md5="d64446108dff7be324ae96c683b7b04e"/>
		<file filename="templates/widgets/navigation/children.tpl" md5="2f26fdaa35d28a1a094699a825db64d8"/>
		<file filename="templates/widgets/navigation/siblings.tpl" md5="e02e7719cfb212e4d9f5637b396e5f10"/>
		<file filename="templates/widgets/navigation/siblingsandchildren.tpl" md5="2f26fdaa35d28a1a094699a825db64d8"/>
		<file filename="templates/widgets/navigation/view.tpl" md5="629c5fcb1cd7f3ecddff0451bc1eee7a"/>
	</view>
	<pages>
		<page baseurl="/Navigation" admin="1" access="" title="Navigation Listings" group="Theme and Layouts"/>
	</pages>
	<widgets>
		<widget baseurl="/navigation/siblings" title="Page Siblings Nav"/>
		<widget baseurl="/navigation/siblingsandchildren" title="Page Siblings w/Children Nav"/>
		<widget baseurl="/navigation/children" title="Page Children Nav"/>
	</widgets>
	<assets>
		<file filename="assets/js/navigation/manager.js" md5="e7852b3c06f5b208e35b1cb5ad08f84f"/>
	</assets>
	<upgrades>
		<upgrade from="0.0.1-dev1" to="1.9.0"/>
		<upgrade from="1.9.0" to="1.9.1"/>
		<upgrade from="1.9.1" to="2.0.0"/>
		<upgrade from="2.0.0" to="2.1.0"/>
		<upgrade from="2.1.0" to="2.1.1"/>
		<upgrade from="2.1.1" to="2.1.2"/>
		<upgrade from="2.1.2" to="2.1.3"/>
		<upgrade from="2.1.3" to="2.1.4"/>
		<upgrade from="2.1.4" to="2.1.5"/>
		<upgrade from="2.1.5" to="2.1.6"/>
		<upgrade from="2.1.6" to="2.1.7"/>
		<upgrade from="2.1.7" to="2.1.8"/>
		<upgrade from="2.1.8" to="2.1.9"/>
	</upgrades>
	<authors>
		<author name="Charlie Powell" email="charlie@eval.bz"/>
	</authors>
	<licenses>
		<license url="http://www.gnu.org/licenses/agpl-3.0.txt">
			GNU Affero General Public License v3
		</license>
	</licenses>
</component>

=== WortTech/coreplus/src/components/nonce/component.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component PUBLIC "SYSTEM" "http://corepl.us/api/2_4/component.dtd">
<component xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="Nonce" version="1.0.2-1~bpo268">
	<requires>
		<require name="Core" type="component" version="2.5.1"/>
	</requires>
	<hooks>
		<hook name="/cron/hourly" call="NonceModel::Cleanup"/>
	</hooks>
	<files>
		<file filename="CHANGELOG" md5="844328338571981da0b6d7b9221df2d5"/>
		<file filename="README.md" md5="5bcf92183d0ab8d2045c82f264e66369"/>
		<file filename="component.xml" md5="8da5da316a129c28e4125eaa44f4fa36"/>
		<file filename="models/NonceModel.php" md5="1184758472a7424ee57da24d2127f171">
			<class name="NonceModel"/>
		</file>
		<file filename="tests/NonceTest.php" md5="3d2fec97d478f40698ab341353ac1bf5">
			<class name="NonceTest"/>
		</file>
	</files>
	<upgrades>
		<upgrade from="1.0.0" to="1.0.1"/>
		<upgrade from="1.0.1" to="1.0.2"/>
		<upgrade from="1.0.2" to="1.0.2-1~bpo268"/>
	</upgrades>
	<description>
		This component provides support for securely generating nonces http://en.wikipedia.org/wiki/Cryptographic_nonce
	</description>
	<smartyplugins/>
	<authors>
		<author name="Charlie Powell" email="charlie@eval.bz"/>
		<author name="Charlie Powell &lt;charlie@eval.bz"/>
	</authors>
	<licenses>
		<license url="http://www.gnu.org/licenses/agpl-3.0.txt">
			GNU Affero General Public License v3
		</license>
	</licenses>
</component>

=== WortTech/coreplus/components/cron/component.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component PUBLIC "SYSTEM" "http://corepl.us/api/2_1/component.dtd">
<component xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="Cron" version="1.0.0">
	<hooks>
		<hookregister name="/cron/hourly" description="Hourly hook called from the cron system"/>
		<hookregister name="/cron/daily" description="Daily hook called from the cron system"/>
		<hookregister name="/cron/weekly" description="Weekly hook called from the cron system"/>
		<hookregister name="/cron/monthly" description="Monthly hook called from the cron system"/>
	</hooks>
	<permissions>
		<permission key="/cron/viewlog" description="View log of cron jobs that have run"/>
	</permissions>
	<pages>
		<page access="p:/cron/viewlog" admin="1" baseurl="/cron/admin" title="Cron Results"/>
	</pages>
	<view searchdir="templates"></view>
	<files>
		<file filename="CHANGELOG" md5="e250dd06d91462497e79838d1e67bf53"/>
		<file filename="README.md" md5="d03dd621fdcc3aab5a50b9e88b361409"/>
		<file filename="controllers/CronController.php" md5="12dbb435473ee2308047456d2ef6a502">
			<controller name="CronController"/>
		</file>
		<file filename="models/CronLogModel.php" md5="72c89926879485ae78343c36b5330c84">
			<class name="CronLogModel"/>
		</file>
	</files>
	<authors>
		<author name="Charlie Powell" email="charlie@eval.bz"/>
	</authors>
</component>

=== WortTech/coreplus/src/components/google/component.xml
<?xml version="1.0"?>
<!DOCTYPE component PUBLIC "SYSTEM" "http://corepl.us/api/2_4/component.dtd">
<component xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.4.0" name="Google" execmode="web">
	<requires>
		<require name="core" type="component" version="3.4.0" operation="ge"/>
	</requires>
	<provides>
		<provide version="3.12" name="GoogleMaps" type="library"/>
		<provide version="1.1.0" name="GoogleAnalytics" type="library"/>
		<provide version="1.1.0" name="GoogleAnalytics" type="component"/>
	</provides>
	<hooks>
		<hook name="/core/page/preexecute" call="\Google\Analytics\Helper::InstallTracking"/>
		<hook name="/core/page/error-404" call="\Google\CSE\Helper::SiteSearch"/>
	</hooks>
	<description>
		Provides (in theory), many of the Google API products.
	</description>
	<configs>
		<config key="/googlemaps/enterprise/privatekey" type="string" default="" description="Private key for Google Maps Enterprise"/>
		<config key="/googlemaps/enterprise/clientname" type="string" description="Client name for Google Maps Enterprise"/>
		<config key="/google-analytics/accountid" type="string" default="" title="Google Account ID" description="This is the Account ID (sometimes called 'Web Property ID') listed for this account in google analytics.  Leaving this blank will disable GA; likewise populating it will automatically enable GA."/>
		<config key="/google/tagmanager/tagid" type="string" default="" title="Google Tag ID" description="If you use Tag Manager to manage tags, enter your tag ID here &lt;em&gt;instead of&lt;/em&gt; your account ID."/>
		<config key="/google/cse/key" type="string" default="" description="The cx for Google CSE Site Search"/>
	</configs>
	<pages>
		<page baseurl="/google/configure" title="Google Keys and Apps" group="Configure" access="g:admin" admin="1" selectable="0"/>
	</pages>
	<files>
		<file filename="CHANGELOG" md5="d12a12d43442d1a22269cf26a54764fb"/>
		<file filename="controllers/GoogleController.php" md5="54d2494188cb6d9c37fc41b1eb56f09f">
			<controller name="GoogleController"/>
		</file>
		<file filename="libs/google/CSE/Helper.php" md5="dc2a7df940960944b36541357309b1c6">
			<class name="Google\CSE\Helper"/>
		</file>
		<file filename="libs/google/analytics/Helper.php" md5="739c3de8a435882d8d71b59b471a6ddc">
			<class name="Google\Analytics\Helper"/>
		</file>
		<file filename="libs/google/maps/GeocodeRequest.php" md5="29b8a83d0e136b1dd5027c247b3568f2">
			<class name="Google\Maps\GeocodeRequest"/>
		</file>
		<file filename="libs/google/maps/GeocodeResponse.php" md5="86c7fd0d5cc93f30e288e76934b3bcd4">
			<class name="Google\Maps\GeocodeResponse"/>
		</file>
	</files>
	<upgrades>
		<upgrade from="1.0.0" to="1.0.1"/>
		<upgrade from="1.0.1" to="1.0.2">
			<!-- Remove the old component's page on upgrade. -->
			<dataset action="delete" table="page">
				<datasetwhere>baseurl = /googleapi/configure</datasetwhere>
			</dataset>
		</upgrade>
		<upgrade from="1.0.2" to="1.1.0"/>
		<upgrade from="1.1.0" to="1.2.0"/>
		<upgrade from="1.2.0" to="1.2.1"/>
		<upgrade from="1.2.1" to="1.3.0"/>
		<upgrade from="1.3.0" to="1.3.1"/>
		<upgrade from="1.3.1" to="1.4.0"/>
	</upgrades>
	<view>
		<file filename="templates/pages/google/configure.tpl" md5="a3fc7915404242b727080991ab014cda"/>
	</view>
	<authors>
		<author name="Charlie Powell" email="charlie@eval.bz"/>
		<author name="Nicholas Hinsch" email="nicholas@eval.bz"/>
	</authors>
	<licenses>
		<license url="http://www.gnu.org/licenses/agpl-3.0.txt">
			GNU Affero General Public License v3
		</license>
	</licenses>
</component>

=== WortTech/coreplus/components/markdown-browser/component.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "http://corepl.us/api/2_1/component.dtd">
<component xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0.1" name="markdown-browser" execmode="web">
	<requires>
		<require name="core" type="component"/>
		<require name="markdown" type="component" version="1.2.5" operation="ge"/>
	</requires>
	<description>
		Provides an inline browser experience for markdown files.
	</description>
	<files>
		<file filename="controllers/MarkdownBrowserController.php" md5="7c0eb6ef5bc079af1f4f46a50532f992">
			<controller name="MarkdownBrowserController"/>
		</file>
	</files>
	<view searchdir="templates">
		<file filename="templates/pages/markdownbrowser/index.tpl" md5="ced87d369e77f7553c285189d67c5cc7"/>
		<file filename="templates/pages/markdownbrowser/index.tpl" md5="2dfc8f64c4fe06140d998bc39464bbcf"/>
		<file filename="templates/pages/markdownbrowser/update.tpl" md5="f9e09c641e7125acc9f3f59ef54dd9cb"/>
		<file filename="templates/pages/markdownbrowser/view-file.tpl" md5="35d194b1b49f068ad8df448098ed7f7c"/>
		<file filename="templates/pages/markdownbrowser/view-listing.tpl" md5="c2c174a157752750e0f51f8b0acddc8b"/>
	</view>
	<pages>
		<page baseurl="/markdownbrowser" admin="1" widget="0" access="g:admin" title="Markdown Directory Listings"/>
	</pages>
	<upgrades>
		<upgrade from="1.0.0" to="1.0.1"/>
	</upgrades>
	<authors>
		<author name="Charlie Powell" email="charlie@eval.bz"/>
	</authors>
	<licenses>
		<license url="http://www.gnu.org/licenses/agpl-3.0.txt">
			GNU Affero General Public License v3
		</license>
	</licenses>
</component>

=== WortTech/coreplus/src/components/content/component.xml
<?xml version="1.0"?>
<!DOCTYPE component PUBLIC "SYSTEM" "http://corepl.us/api/2_4/component.dtd">
<component xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="3.1.0" name="Content" execmode="web" logo="assets/images/logos/content.png">
	<requires>
		<require name="core" type="component" version="6.2.0" operation="ge"/>
	</requires>
	<permissions>
		<permission key="/content/manage_all" description="Manage Site Content"/>
	</permissions>
	<widgets>
		<widget baseurl="/contentadmin/quickdraft" title="Quick Draft" installable="/admin"/>
		<widgetcreate title="Content Area" class="ContentWidget"/>
	</widgets>
	<files>
		<file filename="CHANGELOG" md5="95731348a3305927c51532b80b7631bd"/>
		<file filename="controllers/ContentController.php" md5="257cc521aa0d20e30e657a219b1e43c9">
			<controller name="ContentController"/>
		</file>
		<file filename="i18n/strings.yml" md5="03d1435baa1b6984b25cf8199dbaea8f"/>
		<file filename="models/ContentModel.php" md5="7d24ea7784ccc04a9bba62b188a3d6ca">
			<class name="ContentModel"/>
		</file>
		<file filename="upgrades/310_page_updates.php" md5="549b9de9daba51cff04fe6c2cd6d6db1"/>
		<file filename="widgets/ContentAdminWidget.php" md5="b72ef60f5c4b7470bebcf5c238940013">
			<class name="ContentAdminWidget"/>
		</file>
		<file filename="widgets/ContentWidget.php" md5="75874895c89d80bf137a2cf3787081aa">
			<class name="ContentWidget"/>
		</file>
	</files>
	<pages>
		<page title="t:STRING_NEW_CONTENT_PAGE" baseurl="/content/create" access="p:/content/manage_all" admin="1" group="t:STRING_CONTENT"/>
		<pagecreate title="t:STRING_CONTENT_PAGE" baseurl="/content/create" description="t:MESSAGE_CONTENT_PAGE"/>
	</pages>
	<description>
		Provides basic HTML page functionality.
	</description>
	<view searchdir="templates">
		<file filename="templates/pages/content/create.tpl" md5="1f45af7838e6eb4421220a6dd5a8428d"/>
		<file filename="templates/pages/content/delete.tpl" md5="64255b05d03ba0b58cbacb107e2b2dff"/>
		<file filename="templates/pages/content/edit.tpl" md5="1f45af7838e6eb4421220a6dd5a8428d"/>
		<file filename="templates/pages/content/view.tpl" md5="f9a40b24658d333da22f7726de3d032e"/>
		<file filename="templates/pages/content/view/markdown.tpl" md5="6d535f0b3cb7bbabdd70b9e1935bf034"/>
		<file filename="templates/pages/content/view/option1.tpl" md5="4c8037182441dcac26d7f31496ac2a1a"/>
		<file filename="templates/widgets/content/execute.tpl" md5="0db0ff3eae107a310d9b9fe853452575"/>
		<file filename="templates/widgets/contentadmin/quickdraft.tpl" md5="c97347fb8b98c3dfd8df2430db7572ef"/>
	</view>
	<upgrades>
		<upgrade from="0.0.1-dev1" to="1.9.0"/>
		<upgrade from="1.9.0" to="1.9.1"/>
		<upgrade from="1.9.1" to="1.9.2"/>
		<upgrade from="1.9.2" to="1.9.3"/>
		<upgrade from="1.9.3" to="1.9.4"/>
		<upgrade from="1.9.4" to="1.9.5"/>
		<upgrade from="1.9.5" to="1.9.6"/>
		<upgrade from="1.9.6" to="2.0.0"/>
		<upgrade from="2.0.0" to="2.0.1b1"/>
		<upgrade from="2.0.0" to="2.0.1"/>
		<upgrade from="2.0.1b1" to="2.0.1"/>
		<upgrade from="2.0.1" to="2.0.2"/>
		<upgrade from="2.0.2" to="2.0.3"/>
		<upgrade from="2.0.3" to="2.0.4"/>
		<upgrade from="2.0.4" to="2.1.0"/>
		<upgrade from="2.1.0" to="2.2.0">
			<php file="upgrades/310_page_updates.php"/>
		</upgrade>
		<upgrade from="2.2.0" to="2.3.0"/>
		<upgrade from="2.3.0" to="2.3.1"/>
		<upgrade from="2.3.1" to="2.4.0"/>
		<upgrade from="2.4.0" to="2.4.1"/>
		<upgrade from="2.4.1" to="2.4.2"/>
		<upgrade from="2.4.2" to="2.5.0"/>
		<upgrade from="2.5.0" to="2.5.1"/>
		<upgrade from="2.5.1" to="2.5.2"/>
		<upgrade from="2.5.2" to="3.0.0"/>
		<upgrade from="3.0.0" to="3.0.1"/>
		<upgrade from="3.0.1" to="3.1.0"/>
	</upgrades>
	<assets>
		<file filename="assets/images/logos/content.png" md5="86beb406ad3daac3eabb800366fc1bb7"/>
		<file filename="assets/images/previews/templates/widgets/content/custom-content-area-140.png" md5="673cfa327007694704fe95e47dcc9ec0"/>
		<file filename="assets/images/previews/templates/widgets/content/custom-content-area-210.png" md5="4908ee304cc74dadd78bf4eeddf5c12c"/>
		<file filename="assets/images/previews/templates/widgets/content/custom-content-area.png" md5="f8cea628a881b575aecfa54f1fd32500"/>
	</assets>
</component>

=== WortTech/coreplus/src/components/jquery-lightbox/component.xml
<?xml version="1.0"?>
<!DOCTYPE component PUBLIC "SYSTEM" "http://corepl.us/api/2_4/component.dtd">
<component xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5~core3" name="JQuery-lightbox" execmode="web">
	<requires>
		<require name="core" type="component" version="2.1.0" operation="ge"/>
		<require name="jquery" type="library" version="1.4" operation="ge"/>
		<require name="fontawesome" type="library" version="4.0.0" operation="ge"/>
	</requires>
	<provides>
		<library name="JQuery.lightbox"/>
		<scriptlibrary name="jquery.lightbox" call="JQueryLightbox::Load"/>
	</provides>
	<assets>
		<file filename="assets/css/images/lightbox-blank.gif" md5="fc94fb0c3ed8a8f909dbc7630a0987ff"/>
		<file filename="assets/css/images/lightbox-btn-close.gif" md5="2c38ae5be85141bf8867c9523f4bc357"/>
		<file filename="assets/css/images/lightbox-btn-next.gif" md5="23414965ebe526012e473c1d4d65d4e7"/>
		<file filename="assets/css/images/lightbox-btn-prev.gif" md5="5a9118de4ef6226473190d6e82f6d80d"/>
		<file filename="assets/css/images/lightbox-ico-loading.gif" md5="b5fe8df97005341f898e2cf84e68de01"/>
		<file filename="assets/css/jquery.lightbox-0.5.css" md5="96ffc5ef3f274ad20bc77e293a8b0722"/>
		<file filename="assets/js/jquery.lightbox-0.5.js" md5="1ef2f8dd5868dc9571821afc7ca7da27"/>
		<file filename="assets/js/jquery.lightbox-0.5.min.js" md5="392188831ef280bf9d4e71cdd12d4f17"/>
	</assets>
	<files>
		<file filename="CHANGELOG" md5="d8a552afc35aa7cd068a7869b9dc02ac"/>
		<file filename="JQueryLightbox.lib.php" md5="5a1333e1703f65954cf15c6fe723bd8d">
			<class name="JQueryLightbox"/>
		</file>
	</files>
	<description>
		Query lightBox plugin is simple, elegant, unobtrusive, no need extra markup and is used to overlay images on the current page through the power and flexibility of jQuery&#xB4;s selector.
		lightBox is a plugin for jQuery. It was inspired in Lightbox JS by Lokesh Dhakar.
		Visit http://leandrovieira.com/projects/jquery/lightbox/ for more informations about this jQuery plugin
	</description>
	<upgrades>
		<upgrade from="0.5~core1" to="0.5~core2"/>
		<upgrade from="0.5~core2" to="0.5~core3"/>
	</upgrades>
	<authors>
		<author name="Leandro Vieira Pinho"/>
	</authors>
	<licenses>
		<license url="http://creativecommons.org/licenses/by-sa/2.5/br/deed.en_US">
			CCAttribution-ShareAlike 2.5 Brazil
		</license>
	</licenses>
</component>
