=== WortTech/coreplus/docs/schemas/theme.dtd
<!--
    PUBLIC ID: -//coreplus//vocabulary//EN
    SYSTEM ID: http://corepl.us/api/2_4/theme.dtd

	Last revision date: 2013.05.12
-->

<!--
	An example how to use this DTD from your XML document:

	<?xml version="1.0"?>
	<!DOCTYPE theme SYSTEM "http://corepl.us/api/2_4/theme.dtd">

	<theme>
	...
	</theme>
-->

<!--
	Theme is the main container for everything for a given... well, theme.
	It's the root node, and each theme can only contain one theme.xml, which contains only one theme directive.

	The theme directive MUST have a name and version attribute.
	The name MUST match the theme's directory, (capitalization is optional).
	The version SHOULD start with a number, and ideally have minor and point revisions, optionally with a third party flag at the end.
-->
<!ELEMENT theme ((assets|skins|otherfiles|upgrades|screenshots)?)>
<!ATTLIST theme
	name CDATA #REQUIRED
	version CDATA #REQUIRED
	xmlns:xsi CDATA #FIXED "http://www.w3.org/2001/XMLSchema-instance"
>


<!--- Put your DTDDoc comment here. -->
<!ELEMENT assets (file)*>
<!ELEMENT skins (file)*>
<!ELEMENT otherfiles (file)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT file EMPTY>
<!ATTLIST file
	md5 CDATA #IMPLIED
	filename CDATA #REQUIRED
	title CDATA #IMPLIED
>


<!--- Set of site configuration options -->
<!ELEMENT configs (config)*>

<!--- Each configuration option, editable from within system configuration -->
<!ELEMENT config EMPTY>
<!ATTLIST config
	key CDATA #REQUIRED
	type CDATA #IMPLIED
	options CDATA #IMPLIED
	description CDATA #IMPLIED
	default CDATA #IMPLIED
>

<!--- User config options, since they're usually defined by the components. -->
<!ELEMENT userconfigs (userconfig)*>

<!--- The actual user configuration option, contained within uesrconfigs -->
<!ELEMENT userconfig EMPTY>
<!ATTLIST userconfig
	key CDATA #REQUIRED
	name CDATA #REQUIRED
	formtype CDATA #IMPLIED
	default CDATA #IMPLIED
	options CDATA #IMPLIED
	weight CDATA #IMPLIED
	onregistration (0|1) "1"
	onedit (0|1) "1"
	searchable (0|1) "0"
	required (0|1) "0"
	validation CDATA #IMPLIED
>


<!--- Put your DTDDoc comment here. -->
<!ELEMENT upgrades (upgrade)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT upgrade (dataset|phpfileinclude)*>
<!ATTLIST upgrade
	to CDATA #IMPLIED
	from CDATA #IMPLIED
>

<!--
Execute a low-level dataset operation on the installation or upgrade.
-->
<!ELEMENT dataset (datasetset|datasetwhere|datasetrenamecolumn)*>
<!ATTLIST dataset
	action (update|insert|delete|alter) #REQUIRED
	table CDATA #REQUIRED
>

<!--
	The "SET" clause for datasets.  Useful for UPDATE and INSERT statements.
	The only attribute (which is required), is "key" and the nodeValue is the value that is set for that key.
-->
<!ELEMENT datasetset (#PCDATA)>
<!ATTLIST datasetset
	key CDATA #REQUIRED
>

<!--
	The "WHERE" clause for datasets.  Useful for all types of statements.
	The nodeValue here is the where statement, which is parsed via the dataset system.
-->
<!ELEMENT datasetwhere (#PCDATA)>

<!--
	The system cannot handle renames natively, as a renamed column in the schema is seen as a new column.
	This will allow you to rename a column in the schema during an upgrade.

	Please note, this is ONLY applicable with the "alter" action in the dataset.
-->
<!ELEMENT datasetrenamecolumn (EMPTY)>
<!ATTLIST datasetrenamecolumn
	oldname CDATA #REQUIRED
	newname CDATA #REQUIRED
>

<!-- The phpfileinclude allows upgrades and installs to call a custom php file to be executed automatically. -->
<!ELEMENT phpfileinclude (#PCDATA)>


<!ELEMENT screenshots (screenshot)*>
<!ELEMENT screenshot EMPTY>
<!ATTLIST screenshot
	file #REQUIRED
	title #IMPLIED
>

=== WortTech/coreplus/src/themes/base-v3/theme.xml
<?xml version="1.0"?>
<!DOCTYPE theme PUBLIC "SYSTEM" "http://corepl.us/api/2_4/theme.dtd">
<theme xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="2.1.1" name="Base V3">
	<assets>
		<file filename="assets/css/print.css" md5="f9e2244b2d427f9c5104e63055b6a055"/>
		<file filename="assets/css/print.css.map" md5="27006773d93382d6e8036f7081571452"/>
		<file filename="assets/css/print.min.css" md5="75736c845100387d6e874fc6de1b8d61"/>
		<file filename="assets/css/styles.css" md5="2231b045d52b1434912550794d99df60"/>
		<file filename="assets/css/styles.css.map" md5="6a04e9d13f63a42b407ec3d883384b41"/>
		<file filename="assets/css/styles.min.css" md5="694befd7d4292b52d41987a11fef1b9f"/>
		<file filename="assets/css/tinymce/content.css" md5="ed7226458bd0a4ffbcc8d537a994b2b9"/>
		<file filename="assets/css/tinymce/content.css.map" md5="173c7d60e6749ac236b8869166c53685"/>
		<file filename="assets/css/tinymce/content.min.css" md5="ed2f40bf121b7f47b902eef0a072910d"/>
	</assets>
	<skins default="basic.tpl" admindefault="wide.tpl">
		<file filename="basic.tpl" md5="f46f9bd07703f36154fc36ff8359a008" title=""/>
		<file filename="blank.tpl" md5="e0fe07062c844b9a1353d71edf5cc025" title=""/>
		<file filename="wide.tpl" md5="316ce2d576e183cdd9255b3b8bfe4387" title=""/>
		<file filename="print.tpl" md5="f82af65b975d46d94be3bbcba910a1c5" title=""/>
		<file filename="email_basic.tpl" md5="c7ecebc5fb09b70840373e0577ac03d7" title="basic"/>
	</skins>
	<configs>
		<config key="/theme/site_logo" mapto="THEME_SITE_LOGO" form-attributes="type:file;basedir:public/logo/;accept:image/*;"/>
		<config key="/theme/listing_type" mapto="THEME_LISTING_TYPE" type="string" default="None" form-attributes="type:select;" options="None|Organization|Place|LocalBusiness|Airline|AnimalShelter|AutomotiveBusiness|ChildCare|Corporation|DryCleaningOrLaundry|EducationalOrganization|EmergencyService|EmploymentAgency|EntertainmentBusiness|FinancialService|FoodEstablishment|GovernmentOffice|GovernmentOrganization|HealthAndBeautyBusiness|HomeAndConstructionBusiness|InternetCafe|Library|LodgingBusiness|MedicalOrganization|NGO|PerformingGroup|ProfessionalService|RadioStation|RealEstateAgent|RecyclingCenter|SelfStorage|ShoppingCenter|SportsActivityLocation|SportsOrganization|Store|TelevisionStation|TouristInformationCenter|TravelAgency"/>
		<config key="/theme/listing_name" mapto="THEME_LISTING_NAME"/>
		<config key="/theme/listing_address" mapto="THEME_LISTING_ADDRESS" title="Listing Physical Address"/>
		<config key="/theme/listing_city" mapto="THEME_LISTING_CITY" title="Listing City"/>
		<config key="/theme/listing_province" mapto="THEME_LISTING_PROVINCE" title="Listing Province/State"/>
		<config key="/theme/listing_postal" mapto="THEME_LISTING_POSTAL" title="Listing Postal/Zip"/>
		<config key="/theme/listing_phone" mapto="THEME_LISTING_PHONE" title="Listing Phone Number"/>
		<config key="/theme/listing_fax" mapto="THEME_LISTING_FAX" title="Listing Fax Number"/>
		<config key="/theme/listing_email" mapto="THEME_LISTING_EMAIL" title="Listing Email Address"/>
		<config key="/theme/listing_hours" mapto="THEME_LISTING_HOURS" title="Listing Hours" type="text" description="Open hours of this business.    For multiple records, please list each record on its own line in the format of &quot;Machine Version Days/Time|Human Readable Version Days/Time&quot;.    &lt;br/&gt;&lt;br/&gt;    * Multiple days can be listed with commas ',' separating each day.&lt;br/&gt;    * Day or time ranges are specified using a hyphen '-'.&lt;br/&gt;    * Days are specified using the following two-letter combinations: Mo, Tu, We, Th, Fr, Sa, Su.&lt;br/&gt;    * Times are specified using 24:00 time. For example, 3pm is specified as 15:00.&lt;br/&gt;    * EXAMPLE: &quot;Tu,Th 16:00-20:00|Tuesdays and Thursdays 4-8pm&quot;&lt;br/&gt;    * EXAMPLE: &quot;Mo-Su|24-hours a day, 7-days a week!&quot;&lt;br/&gt;"/>
		<config key="/theme/social_link_facebook" mapto="THEME_SOCIAL_FACEBOOK"/>
		<config key="/theme/social_link_foursquare" mapto="THEME_SOCIAL_FOURSQUARE"/>
		<config key="/theme/social_link_github" mapto="THEME_SOCIAL_GITHUB"/>
		<!-- github-square -->
		<config key="/theme/social_link_gittip" mapto="THEME_SOCIAL_GITTIP"/>
		<config key="/theme/social_link_gplus" mapto="THEME_SOCIAL_GPLUS"/>
		<!-- google-plus-square -->
		<config key="/theme/social_link_instagram" mapto="THEME_SOCIAL_INSTAGRAM"/>
		<config key="/theme/social_link_linkedin" mapto="THEME_SOCIAL_LINKEDIN"/>
		<config key="/theme/social_link_pinterest" mapto="THEME_SOCIAL_PINTEREST"/>
		<!-- pinterest-square -->
		<config key="/theme/social_link_twitter" mapto="THEME_SOCIAL_TWITTER"/>
		<!-- twitter-square -->
		<config key="/theme/social_link_vimeo" mapto="THEME_SOCIAL_VIMEO"/>
		<config key="/theme/social_link_youtube" mapto="THEME_SOCIAL_YOUTUBE"/>
		<config key="/theme/social_link_generic" mapto="THEME_SOCIAL_GENERIC"/>
		<!-- globe -->
	</configs>
	<emailskins default="email_basic.tpl">
		<file filename="email_basic.tpl"/>
	</emailskins>
	<otherfiles>
		<file filename="CHANGELOG" md5="cd5cc0299b1f4e24a229a9865617e42f"/>
		<file filename="assets/scss/_collapsible_fieldsets.scss" md5="c34fcba3463f69af6cd82dec79526d75"/>
		<file filename="assets/scss/_content.scss" md5="e6265d8e793f893d8ea50c361dfa008d"/>
		<file filename="assets/scss/_controls.scss" md5="bd76b95f098ebf71b68de573c2ee31ed"/>
		<file filename="assets/scss/_debugging.scss" md5="c1198bfbb9dfde4845b95f855ab3d6a1"/>
		<file filename="assets/scss/_filters_and_pagination.scss" md5="b5eada7f048b7e236099bc6fa2b79ef0"/>
		<file filename="assets/scss/_form_elements.scss" md5="fbeffbc3e985af3b98d1dc2f9726cf4a"/>
		<file filename="assets/scss/_layout.scss" md5="42c07a5ecf89d6bf6c0806435c615674"/>
		<file filename="assets/scss/_listing_tables.scss" md5="2e8e9d6be0b82a493d0b7429d1732af8"/>
		<file filename="assets/scss/_messages.scss" md5="002d7e2910f33c36ff9bcccb9a49e2ed"/>
		<file filename="assets/scss/_print.scss" md5="f3dd7a5f96e67e8d2156b5887ea785d4"/>
		<file filename="assets/scss/_screen.scss" md5="616a30b3d90d734a28c0b429991eb77e"/>
		<file filename="assets/scss/_variables.scss" md5="9ce0aaa22a7a985d1b60de8e82f3b1cc"/>
		<file filename="assets/scss/pages/_admin_health.scss" md5="8f5e2f2aab639df930a16c8804e123a5"/>
		<file filename="assets/scss/pages/_theme.scss" md5="1039df69f0df35e4c7c9883a109ef103"/>
		<file filename="assets/scss/pages/_updater.scss" md5="071f9f71dda94d07e8423f02e811e72b"/>
		<file filename="assets/scss/pages/_user.scss" md5="bb3fdf298ed68cf238227e583a7cca6c"/>
		<file filename="assets/scss/pages/_widgets.scss" md5="13db361c6afd511138cf054c9cafebab"/>
		<file filename="assets/scss/print.scss" md5="d1d80005e0cff66c29a89e531ad2b56a"/>
		<file filename="assets/scss/styles.scss" md5="dfdf7bccc347ef946b24b38479281711"/>
		<file filename="assets/scss/tinymce/content.scss" md5="e9344c1b36962c17c7ce839307df5cc4"/>
		<file filename="assets/scss/vendor/_normalize.scss" md5="7caceed677229c6cc84aa3f4754ff3a4"/>
		<file filename="assets/scss/vendor/bitters/_base.scss" md5="7166d9a919b6658b127e59de676742fc"/>
		<file filename="assets/scss/vendor/bitters/_buttons.scss" md5="077d78fc15392f4eb9254874b9182e2b"/>
		<file filename="assets/scss/vendor/bitters/_forms.scss" md5="a06daf9497b0098a4cbd8f01ac7ca854"/>
		<file filename="assets/scss/vendor/bitters/_grid-settings.scss" md5="51dbb58d30497d6f64ec1f60ae98ea16"/>
		<file filename="assets/scss/vendor/bitters/_lists.scss" md5="7a3b9009ddd0f0918c022365e8f1ee04"/>
		<file filename="assets/scss/vendor/bitters/_tables.scss" md5="cafb19664e2f77f19210eb2e3e784af7"/>
		<file filename="assets/scss/vendor/bitters/_typography.scss" md5="2049ad725c9935cbeb82308d9347ee36"/>
		<file filename="assets/scss/vendor/bitters/_variables.scss" md5="a53af5c9a9769989294a8cdad19390f5"/>
		<file filename="assets/scss/vendor/bourbon/_bourbon-deprecated-upcoming.scss" md5="4b9dca0323049fa7ae17445c761e9271"/>
		<file filename="assets/scss/vendor/bourbon/_bourbon.scss" md5="ba5c920a40274bda46707cf0049dcdb0"/>
		<file filename="assets/scss/vendor/bourbon/addons/_border-color.scss" md5="8818721adc54116481bed9796cde7065"/>
		<file filename="assets/scss/vendor/bourbon/addons/_border-radius.scss" md5="fbabb4c0961590a98e60120ec1b52b29"/>
		<file filename="assets/scss/vendor/bourbon/addons/_border-style.scss" md5="4aa1d2fde3478aba86ea53672ec2834a"/>
		<file filename="assets/scss/vendor/bourbon/addons/_border-width.scss" md5="e0b5f4df87ec0972b663d0725f069457"/>
		<file filename="assets/scss/vendor/bourbon/addons/_buttons.scss" md5="5544b80f657d270d85f3af0b06db3dca"/>
		<file filename="assets/scss/vendor/bourbon/addons/_clearfix.scss" md5="be71d3d65015d1074542b0d804654c8c"/>
		<file filename="assets/scss/vendor/bourbon/addons/_ellipsis.scss" md5="7bbdda101a8becd7ac455fc44f20503c"/>
		<file filename="assets/scss/vendor/bourbon/addons/_font-stacks.scss" md5="e7bd12977efafa0a92f1750bef37478d"/>
		<file filename="assets/scss/vendor/bourbon/addons/_hide-text.scss" md5="4990bfe4f457a8077eaf82080129cf25"/>
		<file filename="assets/scss/vendor/bourbon/addons/_margin.scss" md5="816ca70f6db60c7195fd098aec03400d"/>
		<file filename="assets/scss/vendor/bourbon/addons/_padding.scss" md5="ccf5ee834100e83105923d701f10d6bf"/>
		<file filename="assets/scss/vendor/bourbon/addons/_position.scss" md5="1e8139909d92eff64043fc175fef732b"/>
		<file filename="assets/scss/vendor/bourbon/addons/_prefixer.scss" md5="c5ae2cf35d2a0fefe352f4a283fb9eba"/>
		<file filename="assets/scss/vendor/bourbon/addons/_retina-image.scss" md5="89c85a8e0ca5b1f215f33079a9c3dfcb"/>
		<file filename="assets/scss/vendor/bourbon/addons/_size.scss" md5="2c53fd5a2b9f2fa7d33d083e4741ba47"/>
		<file filename="assets/scss/vendor/bourbon/addons/_text-inputs.scss" md5="9373f7236cc2186e9700ac9a1bc44f98"/>
		<file filename="assets/scss/vendor/bourbon/addons/_timing-functions.scss" md5="99302f14d64c8c13c37a5d1f5ab7752e"/>
