=== WortTech/coreplus/core/component.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/component.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE component SYSTEM "component.dtd">

    <component>
    ...
    </component>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT component (otherfiles|license|author|dbschema|upgrade|provides|hookregister|hook|smartyplugins|library|module|pages|view|install|changelog|description|configs|assets)*>
<!ATTLIST component
    execmode CDATA #IMPLIED
    name CDATA #IMPLIED
    version CDATA #IMPLIED
    xmlns:xsi CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT provides EMPTY>
<!ATTLIST provides
    version CDATA #IMPLIED
    name CDATA #IMPLIED
    type CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT hookregister EMPTY>
<!ATTLIST hookregister
    description CDATA #IMPLIED
    name CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT hook EMPTY>
<!ATTLIST hook
    call CDATA #IMPLIED
    name CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT smartyplugins EMPTY>
<!ATTLIST smartyplugins
    directory CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT library (file)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT file (provides)*>
<!ATTLIST file
    md5 CDATA #IMPLIED
    filename CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT module (file)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT pages (page)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT page EMPTY>
<!ATTLIST page
    title CDATA #IMPLIED
    access CDATA #IMPLIED
    widget CDATA #IMPLIED
    admin CDATA #IMPLIED
    baseurl CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT view (file)*>
<!ATTLIST view
    searchdir CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT install EMPTY>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT changelog (notes|packagemeta)*>
<!ATTLIST changelog
    version CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT packagemeta (packager|maintainer|date)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT date (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT maintainer EMPTY>
<!ATTLIST maintainer
    email CDATA #IMPLIED
    name CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT packager (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT description (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT configs (config)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT config EMPTY>
<!ATTLIST config
    options CDATA #IMPLIED
    description CDATA #IMPLIED
    default CDATA #IMPLIED
    type CDATA #IMPLIED
    key CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT assets (file)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT upgrade EMPTY>
<!ATTLIST upgrade
    to CDATA #IMPLIED
    from CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT notes (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT dbschema EMPTY>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT author EMPTY>
<!ATTLIST author
    email CDATA #IMPLIED
    name CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT license (#PCDATA)>
<!ATTLIST license
    url CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT otherfiles (file)*>

=== WortTech/coreplus/src/components/package-repository/component.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component PUBLIC "SYSTEM" "http://corepl.us/api/2_4/component.dtd">
<component xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="Package Repository" version="1.0.4">
	<configs>
		<config key="/package_repository/base_directory" type="string"/>
		<config key="/package_repository/is_private" default="0" type="boolean"/>
		<config key="/package_repository/description" type="text"/>
		<config key="/package_repository/auto_ip_restrict" default="0" type="boolean"/>
	</configs>
	<permissions>
		<permission key="/package_repository/licenses/manager"/>
		<permission key="/package_repository/view_analytics"/>
	</permissions>
	<pages>
		<page baseurl="/packagerepository" title="Package Repository" rewriteurl="/repo" indexable="1" admin="0" access="*"/>
		<page baseurl="/packagerepositorylicense/admin" title="Package Repository License Manager" admin="1" group="t:STRING_ADMIN" access="p:/package_repository/licenses/manager"/>
		<page baseurl="/packagerepository/config" title="Package Repository Configuration" admin="1" access="g:admin" group="t:STRING_CONFIGURE"/>
		<page baseurl="/packagerepository/analytics" title="t:STRING_PACKAGE_REPOSITORY_ANALYTICS" admin="1" access="p:/package_repository/view_analytics" group="t:STRING_REPORTING"/>
	</pages>
	<files>
		<file filename="CHANGELOG" md5="89b46c11f42aa4031d59131d9a5aa2df"/>
		<file filename="README.md" md5="de233577a6cb1e8d6cb660e9ae9d95ed"/>
		<file filename="assets/scss/package-repository.scss" md5="f1386c9db81b75b581af931c10ac48fe"/>
		<file filename="controllers/PackageRepositoryController.php" md5="fdc1c194b0853d49e3d4bfceccad4203">
			<controller name="PackageRepositoryController"/>
		</file>
		<file filename="controllers/PackageRepositoryLicenseController.php" md5="181fa2ec1c74406f03b5238d8503629f">
			<controller name="PackageRepositoryLicenseController"/>
		</file>
		<file filename="i18n/ar.ini" md5="a8b41ec7ee76f305ca4b3372cbf25f6d"/>
		<file filename="i18n/de.ini" md5="992527fd785e95a33a94bc426b9dc94c"/>
		<file filename="i18n/en.ini" md5="268b07bba4b3a0fb3202cb569164c2a6"/>
		<file filename="i18n/fr.ini" md5="2e54ae729dd18fc82a460f349834a5e8"/>
		<file filename="models/PackageRepositoryLicenseModel.php" md5="e836cd516352361b1ba5ce06138ea1d5">
			<class name="PackageRepositoryLicenseModel"/>
		</file>
	</files>
	<view>
		<file filename="templates/pages/packagerepository/analytics.tpl" md5="4b75bd884d0e5095ed62e526df7a29c7"/>
		<file filename="templates/pages/packagerepository/config.tpl" md5="6795037bf2dc9bde8b4043b07839db46"/>
		<file filename="templates/pages/packagerepository/index.tpl" md5="6de5afe57770779ad5165c095a049e39"/>
		<file filename="templates/pages/packagerepositorylicense/add.tpl" md5="6795037bf2dc9bde8b4043b07839db46"/>
		<file filename="templates/pages/packagerepositorylicense/admin.tpl" md5="0bfc0cac42ab230d9d2d319f63dd8ca3"/>
		<file filename="templates/pages/packagerepositorylicense/edit.tpl" md5="6795037bf2dc9bde8b4043b07839db46"/>
	</view>
	<upgrades>
		<upgrade from="1.0.0" to="1.0.1"/>
		<upgrade from="1.0.1" to="1.0.2"/>
		<upgrade from="1.0.2" to="1.0.3"/>
		<upgrade from="1.0.3" to="1.0.4"/>
	</upgrades>
	<authors>
		<author name="Charlie Powell" email="charlie@evalagency.com"/>
	</authors>
	<assets>
		<file filename="assets/css/package-repository.css" md5="affaed13cc449437ff76f21518160c3d"/>
		<file filename="assets/css/package-repository.css.map" md5="579dbe0b0860c5436195f12d84adc4bb"/>
		<file filename="assets/css/package-repository.min.css" md5="50792fffaef0b0023b392ced664cadd6"/>
	</assets>
</component>

=== WortTech/coreplus/src/components/themeeditor/component.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component PUBLIC "SYSTEM" "http://corepl.us/api/2_1/component.dtd">
<component name="themeeditor" version="1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<authors>
		<author name="Nick Hinsch" email="nicholas@eval.bz"/>
	</authors>
	<files>
		<file filename="CHANGELOG" md5="98c2b74758c36dbdbf671daaa62190ee"/>
		<file filename="README.md" md5="68c52d6b2bf88f7bc2111701385c772a"/>
		<file filename="controllers/ThemeEditorController.php" md5="f8d8cce4db100ca9236926748e0c05a4">
			<controller name="ThemeEditorController"/>
		</file>
		<file filename="models/ThemeEditorItemModel.php" md5="fd6fbfa9743419a93e5d27b565e09cd9">
			<class name="ThemeEditorItemModel"/>
		</file>
	</files>
	<assets>
		<file filename="assets/css/codemirror.css"/>
		<file filename="assets/js/codemirror.js"/>
		<file filename="assets/mode/css/css.js"/>
		<file filename="assets/mode/diff/diff.js"/>
		<file filename="assets/mode/htmlembedded/htmlembedded.js"/>
		<file filename="assets/mode/htmlmixed/htmlmixed.js"/>
		<file filename="assets/mode/javascript/javascript.js"/>
		<file filename="assets/mode/less/less.js"/>
		<file filename="assets/mode/markdown/markdown.js"/>
		<file filename="assets/mode/mysql/mysql.js"/>
		<file filename="assets/mode/perl/perl.js"/>
		<file filename="assets/mode/php/php.js"/>
		<file filename="assets/mode/properties/properties.js"/>
		<file filename="assets/mode/python/python.js"/>
		<file filename="assets/mode/smarty/smarty.js"/>
		<file filename="assets/mode/xml/xml.js"/>
	</assets>
	<view searchdir="templates"/>
</component>

=== WortTech/coreplus/src/components/theme/component.xml
<?xml version="1.0"?>
<!DOCTYPE component PUBLIC "SYSTEM" "http://corepl.us/api/2_4/component.dtd">
<component xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="2.4.3" name="Theme" execmode="web">
	<requires>
		<require name="core" type="component" version="3.5.0" operation="ge"/>
		<require name="jquery" type="library" version="1.7.0" operation="ge"/>
		<require name="jqueryui" type="library" version="1.8.0" operation="ge"/>
	</requires>
	<hooks>
		<hook name="/core/components/loaded" call="ThemeHandler::Load"/>
	</hooks>
	<files>
		<file filename="CHANGELOG" md5="5d4c793fa4044fe1d52786fd604f36b7"/>
		<file filename="controllers/ThemeController.class.php" md5="39b9f4686be70fc025f2d444ef2baf94">
			<controller name="ThemeController"/>
		</file>
		<file filename="functions/common.php" md5="6d8e7b9aa1cb62b63e5233ed4b824b0b"/>
		<file filename="libs/Theme/Theme.php" md5="f4970155987c165172c8a4b56e974407">
			<class name="Theme\Theme"/>
		</file>
		<file filename="libs/ThemeHandler.class.php" md5="f9406dd7a2af3c1e76ae3c90f57dc62f">
			<class name="ThemeHandler"/>
		</file>
		<file filename="models/ThemeTemplateChangeModel.php" md5="4e14433a608d4d43bd55910fb7c9c172">
			<class name="ThemeTemplateChangeModel"/>
		</file>
	</files>
	<view>
		<file filename="templates/pages/theme/editor.tpl" md5="533b2423a66182e692136eefa142f081"/>
		<file filename="templates/pages/theme/index.tpl" md5="bacb86ad000baf6c53b4a525abd455f1"/>
		<file filename="templates/pages/theme/selectstylesheets.tpl" md5="47956fc42e0954353264ab3d2f5c0e59"/>
		<file filename="templates/pages/theme/setdefault.tpl" md5="835a5142fdb7c580502a6413909a89e0"/>
	</view>
	<pages>
		<page baseurl="/theme" admin="1" access="g:admin" title="Theme Manager" group="Theme and Layouts"/>
	</pages>
	<configs>
		<config key="/theme/default_template" type="string" default="basic.tpl" description=""/>
		<config key="/theme/default_admin_template" type="string" default="basic.tpl" description=""/>
		<config key="/theme/default_email_template" type="string" default="" description=""/>
		<config key="/theme/selected" type="string" default="base-v3" description=""/>
	</configs>
	<assets>
		<file filename="assets/css/theme/admin.css" md5="de1b2508bc649081b8e58fc4d8df2243"/>
		<file filename="assets/css/theme/widgets.css" md5="c30e4f3c1849a829d1bfc47fd9eecd0a"/>
		<file filename="assets/js/theme/widgets.js" md5="0ac5f62b8fb3bddc6c918379a01ed36f"/>
	</assets>
	<description/>
	<upgrades>
		<upgrade from="0.0.1" to="1.9.0"/>
		<upgrade from="1.9.0" to="1.9.1"/>
		<upgrade from="1.9.1" to="1.9.2"/>
		<upgrade from="1.9.2" to="2.0.0"/>
		<upgrade from="2.0.0" to="2.0.1"/>
		<upgrade from="2.0.1" to="2.0.2"/>
		<upgrade from="2.0.2" to="2.0.3b1"/>
		<upgrade from="2.0.3b1" to="2.0.3"/>
		<upgrade from="2.0.3" to="2.0.4"/>
		<upgrade from="2.0.4" to="2.0.5"/>
		<upgrade from="2.0.5" to="2.0.6"/>
		<upgrade from="2.0.6" to="2.1.0"/>
		<upgrade from="2.1.0" to="2.1.1"/>
		<upgrade from="2.1.1" to="2.1.2"/>
		<upgrade from="2.1.2" to="2.1.3"/>
		<upgrade from="2.1.3" to="2.1.4"/>
		<upgrade from="2.1.4" to="2.1.5"/>
		<upgrade from="2.1.5" to="2.2.0"/>
		<upgrade from="2.2.0" to="2.3.0"/>
		<upgrade from="2.3.0" to="2.4.0"/>
		<upgrade from="2.4.0" to="2.4.1"/>
		<upgrade from="2.4.1" to="2.4.2"/>
		<upgrade from="2.4.2" to="2.4.3"/>
	</upgrades>
	<authors>
		<author name="Charlie Powell" email="charlie@evalagency.com"/>
		<author name="Nick Hinsch &lt;nicholas@evalagency.com"/>
		<author name="Nick Hinsch" email="nicholas@evalagency.com"/>
	</authors>
	<licenses>
		<license url="http://www.gnu.org/licenses/agpl.html">
			GNU Affero General Public License v3
		</license>
	</licenses>
</component>

=== WortTech/coreplus/src/components/coolphpcaptcha/component.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "http://corepl.us/api/2_1/component.dtd">
<component xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.3~core5" name="CoolPHPCaptcha" execmode="web">
	<requires>
		<require name="core" type="component"/>
	</requires>
	<provides>
		<provide type="library" name="captcha" version="1.0.0"/>
	</provides>
	<forms>
		<formelement name="captcha" class="FormCaptchaInput"/>
	</forms>
	<description>
		Standard self-hosted version of an image captcha with fully customizable settings.
	</description>
	<configs>
		<config key="/captcha/width" description="Image width" type="int" default="150"/>
		<config key="/captcha/height" description="Image height" type="int" default="60"/>
		<config key="/captcha/minlength" description="Minimum word length" type="int" default="4"/>
		<config key="/captcha/maxlength" description="Maximum word length" type="int" default="5"/>
		<config key="/captcha/linethrough" description="Size of the line to strike through the text, 0 to disable" type="int" default="0"/>
		<config key="/captcha/yperiod" description="Y-Period of the sinewave distortion" type="int" default="12"/>
		<config key="/captcha/yamplitude" description="Y-Amplitude of the sinewave distortion" type="int" default="14"/>
		<config key="/captcha/xperiod" description="X-Period of the sinewave distortion" type="int" default="11"/>
		<config key="/captcha/xamplitude" description="X-Amplitude of the sinewave distortion" type="int" default="2"/>
		<config key="/captcha/maxrotation" description="Maximum degree of rotation for the letters" type="int" default="4"/>
		<config key="/captcha/blur" description="Enable or disable blur on the text" type="boolean" default="false"/>
		<config key="/captcha/formtext" description="Form text for the captcha label" type="string" default="Are you a Human?"/>
	</configs>
	<pages>
		<page baseurl="/simplecaptcha/admin" title="Captcha Tweaks" access="g:admin" admin="1" group="Configure"/>
	</pages>
	<files>
		<file filename="CHANGELOG" md5="c2e471d3003f78b9add51a2634b76000"/>
		<file filename="FormCaptchaInput.class.php" md5="88567b1a36c7e0dbf6c42de32313d74f">
			<class name="FormCaptchaInput"/>
		</file>
		<file filename="SimpleCaptchaController.class.php" md5="8df5664d0ff80f49d1fcde716ca289a4">
			<controller name="SimpleCaptchaController"/>
		</file>
		<file filename="libs/cool-php-captcha/LICENSE.txt" md5="d32239bcb673463ab874e80d47fae504"/>
		<file filename="libs/cool-php-captcha/SimpleCaptcha.class.php" md5="dba8cfdb5e06954b3fa6b5347a0e4859">
			<class name="SimpleCaptcha"/>
		</file>
		<file filename="libs/cool-php-captcha/captcha.php" md5="b5bdd51b42073d3d50a8fc260547c177"/>
		<file filename="libs/cool-php-captcha/example-form.php" md5="12e2cc13f2eb805423236db5d42c3063"/>
		<file filename="libs/cool-php-captcha/example.jpg" md5="c43a4ccb03c2ab8d5daaad15e0c93192"/>
		<file filename="libs/cool-php-captcha/resources/fonts/AntykwaBold.ttf" md5="b9106ffe9631b4ab2e28f3d7accc48a3"/>
		<file filename="libs/cool-php-captcha/resources/fonts/Candice.ttf" md5="9c7bc61ece0a61a85b6e8a59bebef3d2"/>
		<file filename="libs/cool-php-captcha/resources/fonts/Ding-DongDaddyO.ttf" md5="7bc55743d12c71e4594f4b6b918f8917"/>
		<file filename="libs/cool-php-captcha/resources/fonts/Duality.ttf" md5="0a28056baf1a5d86a8b822236462b7cb"/>
		<file filename="libs/cool-php-captcha/resources/fonts/Heineken.ttf" md5="fbe82ed64fbbd2fef712ad10fc2be7cb"/>
		<file filename="libs/cool-php-captcha/resources/fonts/Jura.ttf" md5="33a1ce8894390c3ccf3ad9d0971ccfff"/>
		<file filename="libs/cool-php-captcha/resources/fonts/StayPuft.ttf" md5="59299d5b871590f70b455395c244e8d6"/>
		<file filename="libs/cool-php-captcha/resources/fonts/TimesNewRomanBold.ttf" md5="ed6e29caf3843142d739232aa8642158"/>
		<file filename="libs/cool-php-captcha/resources/fonts/VeraSansBold.ttf" md5="4ebf664c986099acf6d151c62bdb24eb"/>
		<file filename="libs/cool-php-captcha/resources/tools/dictionary-import/README.txt" md5="62eed72b08dd2c38251bd2fda88f5f16"/>
		<file filename="libs/cool-php-captcha/resources/tools/dictionary-import/importwords.php" md5="9e4ba5a658267f7e2058f34d7eced1c8"/>
		<file filename="libs/cool-php-captcha/resources/tools/dictionary-import/sample-words-en.txt" md5="d750dbbc0ffd664f8393f31ceb521e42"/>
		<file filename="libs/cool-php-captcha/resources/tools/dictionary-import/sample-words-es.txt" md5="86e831ec736bb57f624a8cb1462d8c86"/>
		<file filename="libs/cool-php-captcha/resources/words/en.php" md5="ef0f1910e5c269184433ae7a00e41a36"/>
		<file filename="libs/cool-php-captcha/resources/words/es.php" md5="6af474ca4c1918801c3f86b88b30eacb"/>
	</files>
	<view>
		<file filename="templates/forms/elements/formcaptchainput.tpl" md5="266dee08cef5d48db18ddd2d35b33bd1"/>
	</view>
	<upgrades>
		<upgrade from="0.3~cae1" to="0.3~core1"/>
		<upgrade from="0.3~core1" to="0.3~core2"/>
		<upgrade from="0.3~core2" to="0.3~core3"/>
		<upgrade from="0.3~core3" to="0.3~core4"/>
		<upgrade from="0.3~core4" to="0.3~core5"/>
	</upgrades>
	<component></component>
	<authors>
		<author name="Charlie Powell" email="charlie@eval.bz"/>
		<author name="Jose Rodriguez" email="jose.rodriguez@exec.cl"/>
	</authors>
	<licenses>
		<license>GPLv3</license>
	</licenses>
</component>

=== WortTech/coreplus/components/jquery-file-upload/component.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "http://corepl.us/api/2_1/component.dtd">
<component xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="6.9.1~core2" name="jQuery-File-Upload" execmode="web">
	<requires>
		<require name="JQuery" type="library" version="1.6" operation="ge"/>
		<require name="jqueryui" type="library" version="1.8" operation="ge"/>
	</requires>
	<upgrades>
		<upgrade from="6.9.1~core1" to="6.9.1~core2"/>
	</upgrades>
	<description>
		File Upload widget with multiple file selection, drag and drop support, progress bars and preview images for jQuery.
		Supports cross-domain, chunked and resumable file uploads and client-side image resizing.
		This package has been minimized to include support for only PHP based server platforms, since that's all that Core+ runs on.
	</description>
	<forms>
		<formelement name="multifile" class="MultiFileInput"/>
	</forms>
	<files>
		<file filename="CHANGELOG" md5="a34226cdcfd196980367b31119e67de7"/>
		<file filename="README.md" md5="cb22a03a2f5fc8aaf6dcf5a9c2180a66"/>
		<file filename="classes/MultiFileInput.class.php" md5="cbf33dcfa27832339ca1b1e992eb77e8">
			<class name="MultiFileInput"/>
		</file>
		<file filename="controllers/JQueryFileUploadController.php" md5="8df9ebfad218d56b3fdd690245652962">
			<controller name="JQueryFileUploadController"/>
		</file>
		<file filename="misc/cors/postmessage.html" md5="a44b950eba47719cfd9775e16ffdef70"/>
		<file filename="misc/cors/result.html" md5="e07ff3e2fa24130baf5a11c1aa0ba7c0"/>
		<file filename="misc/css/jquery.fileupload-ui.css" md5="a0d23e0880ef82a17d4c3d8fc1490acc"/>
		<file filename="misc/css/style.css" md5="4b836e70afc92c31b62983187ae0b7bc"/>
		<file filename="misc/img/loading.gif" md5="05992d3434d3589b38a3a5431842d38f"/>
		<file filename="misc/img/progressbar.gif" md5="2165b99c89c8431e7165530ccb5f89fb"/>
		<file filename="misc/index.html" md5="e7234e2b7d2a70a2bff02ec2398f8165"/>
		<file filename="misc/package.json" md5="6afd4c268864d5045edd0f161032dfe4"/>
		<file filename="misc/server/gae-go/app.yaml" md5="62779923186fce0d4f8126b14f94daf2"/>
		<file filename="misc/server/gae-go/app/main.go" md5="eb8a167171e69c426b8072a4ae056e0e"/>
		<file filename="misc/server/gae-go/resize/resize.go" md5="8c553454cde68dccb7a342c1881c658b"/>
		<file filename="misc/server/gae-go/static/favicon.ico" md5="9c0ded6158793bdab415f17a7f1ba98d"/>
		<file filename="misc/server/gae-go/static/robots.txt" md5="b6216d61c03e6ce0c9aea6ca7808f7ca"/>
		<file filename="misc/server/gae-python/app.yaml" md5="96d2461ea0e89ac8bb56f11e9b869732"/>
		<file filename="misc/server/gae-python/main.py" md5="e6da5ad137fea8eb68f152c89129254a"/>
		<file filename="misc/server/gae-python/static/favicon.ico" md5="9c0ded6158793bdab415f17a7f1ba98d"/>
		<file filename="misc/server/gae-python/static/robots.txt" md5="b6216d61c03e6ce0c9aea6ca7808f7ca"/>
		<file filename="misc/server/node/package.json" md5="d9760348266ce78a36f8fd77e0e11dca"/>
		<file filename="misc/server/node/server.js" md5="49c115909bb3533d64f77febe2f31206"/>
		<file filename="misc/server/php/index.php" md5="1a2c3909a406faf12c1ff3e68df94a0c"/>
		<file filename="misc/server/php/upload.class.php" md5="d111aea5b9c664d75dc1db6f7f6ba842">
			<class name="UploadHandler"/>
		</file>
		<file filename="misc/test/index.html" md5="f9854e0a6ca74cb493ea70a6bc4e521a"/>
		<file filename="misc/test/test.js" md5="2f21c6e24f3d0623f4cf14d212543ef8"/>
	</files>
	<assets>
		<file filename="assets/css/jquery-file-upload.css" md5="be2f8ac827a0623b2241d3c07263c4b7"/>
		<file filename="assets/js/cors/jquery.postmessage-transport.js" md5="11fe256b13a09546f7280198d8e98239"/>
		<file filename="assets/js/cors/jquery.xdr-transport.js" md5="0927262e8bbd59ec33eda07237e6f19a"/>
		<file filename="assets/js/jquery.fileupload-fp.js" md5="b26df0946db6d77ffcae7d02b7fdfff3"/>
		<file filename="assets/js/jquery.fileupload-ui.js" md5="f594ca00dff11b09c2340d56c7be2766"/>
		<file filename="assets/js/jquery.fileupload.js" md5="5554a67234029282d81603f3b810f02b"/>
		<file filename="assets/js/jquery.iframe-transport.js" md5="64c4919f8d8d06d25f1174f11d7a14e4"/>
		<file filename="assets/js/locale.js" md5="a3e000456648ad121c8aadf7d918a4e7"/>
		<file filename="assets/js/main.js" md5="107bdfd43c84dc9cc817d9e8b3e821e5"/>
		<file filename="assets/js/vendor/jquery.ui.widget.js" md5="34af0fa43f73d5db9d7ff94d218ccdd9"/>
	</assets>
	<view searchdir="templates">
		<file filename="templates/forms/elements/multifileinput.tpl" md5="e0bc14bfc00e74b6979e834a32299510"/>
	</view>
	<authors>
		<author name="Sebastian Tschan"/>
	</authors>
</component>

=== WortTech/coreplus/components/googleanalytics/component.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "component.dtd">
<component xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0.0" name="GoogleAnalytics" execmode="web">
	<requires name="core" type="component"/>
	<hook name="/core/page/prerender" call="GoogleAnalyticsHelper::InstallTracking"/>
	<library>
		<file filename="GoogleAnalyticsHelper.class.php" md5="c1687939d9fb75d2f92ad2b2f49a47f7">
			<provides type="class" name="GoogleAnalyticsHelper"/>
		</file>
	</library>
	<description>
		Provides google analytics integration.
	</description>
	<configs>
		<config key="/google-analytics/accountid" type="string" default="" description="This is the Account ID (sometimes called 'Web Property ID') listed for this account in google analytics."/>
	</configs>
	<changelog version="1.0.0">
		<packagemeta>
			<date>Wed, 28 Sep 2011 03:28:48 -0400</date>
			<maintainer name="Charlie Powell" email="powellc@powelltechs.com"/>
			<packager>CAE2 0.0.6</packager>
		</packagemeta>
		<notes>Initial version</notes>
	</changelog>
	<otherfiles/>
</component>
